### ISSUE TITLE
Package "firebaseui-angular" has an incompatible peer dependency to "@angular/common" (requires "^6.1.2" (extended), would install "8.1.2")

### ISSUE THREAD

**Issue by moblizeitllc** [RaphaelJenni/FirebaseUI-Angular#101]
Exact same issue as in https://github.com/angular/angularfire2/issues/2082

**Comment by PiotrFr** [comment]
Package "firebaseui-angular" has an incompatible peer dependency to "@angular/common" (requires ">=6.1.2", would install "**9.0.0-next.7**")

**Comment by RaphaelJenni** [comment]
Thanks for the report. It totally went under. I'll set it on my todo list.

**Comment by RaphaelJenni** [comment]
Sorry for the long delay. I uploaded a beta version (4.0.1-beta.0). Please give it a try and check if it solved your issue.

**Comment by PiotrFr** [comment]
I am working with 4.0.1-beta.0 without any problems.
