### ISSUE TITLE
Redirect error Android login

### ISSUE THREAD

**Issue by viniciussilverio** [RaphaelJenni/FirebaseUI-Angular#103]
Hi, I'm having a problem when running on Android device, the Google and Facebook logins open in a Chrome window and not inside the app, and after do the login on the page it no redirects to the app, the page keeps open and the app keeps waiting the login.

Android 8.1
Ionic 4

**Comment by tankip** [comment]
i am getting the same problem.
Did you happen to find a solution to it?

**Comment by RaphaelJenni** [comment]
I'm not using ionic, so I can't help you with this issue. Check with the firebaseui team, if they know more, as this plugin only works as a wrapper to use it in angular.

**Comment by RobinGiel** [comment]
@tankip and @viniciussilverio I would advice you to use [https://github.com/jeduan/cordova-plugin-facebook4](url) for facebook if you don't want to have to go via a web browser

**Comment by choopage** [comment]
@viniciussilverio  @tankip  Are you using popup or redirect?

**Comment by tankip** [comment]
@choopage I'm using popup

**Comment by ihorbond** [comment]
@tankip what did you end up doing ? I was about to add this package to my ionic app too

**Comment by kneeki** [comment]
Has a solution for this been discovered? I'm having the same issue when using this package and while following the [official Firebase docs](https://firebase.google.com/docs/auth/web/cordova).

Using Ionic 5 + Cordova to build an Android app. Everything works fine when using `ionic serve --ssl`.

**Comment by tankip** [comment]
@kneeki @ihorbond @choopage  I found a way to do google pop up authentication. I sed the google plus plugin together with firebase. You can check it on this medium post [https://medium.com/enappd/implement-google-login-in-ionic-4-apps-using-firebase-57334bad0910](url)

**Comment by ihorbond** [comment]
I ended up using https://github.com/baumblatt/capacitor-firebase-auth

**Comment by tankip** [comment]
@ihorbond awesome. I will check that one out too.

**Comment by RaphaelJenni** [comment]
Close due to inactivity
