### ISSUE TITLE
'firebase-ui' is not a known element

### ISSUE THREAD

**Issue by viniciusgati** [RaphaelJenni/FirebaseUI-Angular#104]
I have followed the readme and i got this error:

ERROR Error: Uncaught (in promise): Error: Template parse errors:
'firebase-ui' is not a known element:
1. If 'firebase-ui' is an Angular component, then verify that it is part of this module.

**Comment by RaphaelJenni** [comment]
This looks like you haven't imported the firebase ui angular module in the module this component is running in.

**Comment by viniciusgati** [comment]
I have made the same as the Readme... like this:
`@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    AppRoutingModule,
    AngularFireModule.initializeApp(environment.firebaseConfig),
    AngularFireAuthModule,
    FirebaseUIModule.forRoot(firebaseUiAuthConfig)
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}
`

**Comment by viniciusgati** [comment]
@RaphaelJenni the repository is https://github.com/viniciusgati/angular-ionic-firebase-auth-test
same problema reproduced, very simple, new ionic app, install dependecies, configure FirebaseUI

As i have seen on the FirebaseUI-Angular code everything looks good, i will give another try soon.

**Comment by viniciusgati** [comment]
Maybe it is related to angular 8
