### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by hossameldeen** [RaphaelJenni/FirebaseUI-Angular#106]
Just a thank you. Can be closed at anytime. Sorry for the noise.

Seriously: Just used it with email-link authentication. It's awesome. I can't imagine how many days I'd have spent designing the UI & not doing one as good as yours (yup, it's `firebaseui-web`'s but I might have not integrated it but for your library).

Sorry for the noise again. Can be closed silently.

**Comment by RaphaelJenni** [comment]
@hossameldeen Thank you for the kind words. This means allot. The goal of this plugin is solely to make the life easier for other developers. I'm glad that I could help.

**Comment by hossameldeen** [comment]
You're welcome, it did make my life easier. Hope I can one day repay you and people like you with more than words.

Wish you all the best in your life! ^^
