### ISSUE TITLE
Angular 8 Production Build Error (TypeError: Cannot read property 'Length' of undefined)

### ISSUE THREAD

**Issue by awais786327** [RaphaelJenni/FirebaseUI-Angular#107]
First of all thanks for the great stuff, i am developing application and before making **build** everythings going perfect and everything is working fine as expected you can see no error in console

![image](https://user-images.githubusercontent.com/12613564/65957824-51ffe500-e467-11e9-8faa-aeb9c97c38cc.png)

but when i **build** my app using following commands one by one 

- **ng build**, 
- **ng build --aot**, 
- **ng deploy --base-href=/project_name/** (for github pages) 

and test it using lite server **lite-server --baseDir="dist/project-name"** I get the following error

![image](https://user-images.githubusercontent.com/12613564/65957377-19134080-e466-11e9-817e-d450a10de71b.png)

I have tried a couple of solutions mentioned in previous issues like changing **"target": "es5"** in tsconfig.json upgrade to **"firebaseui-angular": "^4.0.0-beta.0"** but none of seems to be work !

This is my **package.json**

![image](https://user-images.githubusercontent.com/12613564/65958856-da7f8500-e469-11e9-90f4-3756d24efbf3.png)

This is my **tsconfig.json**

![image](https://user-images.githubusercontent.com/12613564/65958229-58429100-e468-11e9-917c-4e1b1adfc245.png)

This is my **authencation.module.ts**

![image](https://user-images.githubusercontent.com/12613564/65958579-24b43680-e469-11e9-8180-9c7f259b05cc.png)

This is my **app.module.ts**

![image](https://user-images.githubusercontent.com/12613564/65958623-401f4180-e469-11e9-9da3-15c8016a8643.png)

Any help would be appriciated, Thanks !

**Comment by RaphaelJenni** [comment]
Hi
Sorry for the late response.
Do you still need some help?

**Comment by awais786327** [comment]
no superman you have pretty fast response skills dude btw
