### ISSUE TITLE
Don't reference window object directly

### ISSUE THREAD

**Issue by SachinShekhar** [RaphaelJenni/FirebaseUI-Angular#109]
I can see here in [this service](https://github.com/RaphaelJenni/FirebaseUI-Angular/blob/master/projects/firebaseui-angular-library/src/lib/firebaseui-angular-library.service.ts) that you've referenced window object directly:

```
@Injectable()
export class FirebaseuiAngularLibraryService {
  public firebaseUiInstance: firebaseui.auth.AuthUI;

  constructor(angularFireAuth: AngularFireAuth) {
    // store the firebaseui instance on the window object to prevent double initialization
    if (!(<any>window).firebaseUiInstance) {
      (<any>window).firebaseUiInstance = new firebaseui.auth.AuthUI(angularFireAuth.auth);
    }
    this.firebaseUiInstance = (<any>window).firebaseUiInstance as firebaseui.auth.AuthUI;
  }
}
```

This is not a standard Angular practice. To enforce singleton behavior, there's Dependency Injection system in place. See [this](https://angular.io/guide/singleton-services).

**My Problem:**
Because of this, SSR (Angular Universal) is throwing error.

Consider it as a bug and/or feature request, but please remove window reference.

**Comment by SachinShekhar** [comment]
It seems that this won't fix my issue because you are merely a wrapper and `firebaseui` itself is the main offender to use global window object.

**Comment by coleridge72** [comment]
For anyone else stuck on this (I was) - I got round it by creating a separate module that contains all the sign-in logic and then used angular lazy-loading in the router to access this module. 

In the server.ts file I also had make this route served by the browser.
```
  server.get('/login', function (req, res) {
    res.sendFile(join(distFolder, 'browser', 'index.html'));
 });
```
