### ISSUE TITLE
Ionic 3.5, issue on navigation

### ISSUE THREAD

**Issue by ajonp** [RaphaelJenni/FirebaseUI-Angular#11]
The deeplink actual fires before the login finishes its loading state. Need to be able to release to the next view.

```
    const authObserver = afAuth.authState.subscribe(user => {
      if (!user) {
        this.rootPage = WelcomePage;
      } else {
        if (this.nav.getActive().name) {
          this.nav.setRoot(this.nav.getActive().name);
        }
        else {
          this.rootPage = 'MyStuffPage';
        }
      }
    });
```

if I remove
```
        if (this.nav.getActive().name) {
          this.nav.setRoot(this.nav.getActive().name);
        }
```
It will just stay on the same login page, because the view has already loaded. I need a promise or something to continue forward.

**Comment by RaphaelJenni** [comment]
Hey
Sorry, how can I help you with that? I'm not using ionic, so I don't know how it works exactly. You have to eplaxin it more specific.

**Comment by ajonp** [comment]
@RaphaelJenni can I give you access to my private repo to try it out?

**Comment by RaphaelJenni** [comment]
@ajonp I can give it a try, but I as I said, I haven't worked with ionic yet. So I don't know of how much help I am.

**Comment by ajonp** [comment]
@RaphaelJenni I think what is really needed is the success callbacks. https://github.com/firebase/firebaseui-web#available-callbacks

Then we would be good.

**Comment by RaphaelJenni** [comment]
Well I get that, but why don't you specify the redirect url or do it with the auth observer?

**Comment by ajonp** [comment]
Total user error, my fault!

**Comment by ajonp** [comment]
@RaphaelJenni I am sorry to hit you up on this issue again, but this works great in a browser and fails to forward on mobile. It won't trigger back to the auth subscriber.

app.component.ts
```
      this.afAuth.authState.subscribe(user => {
        if (user && user.uid) {
          //Update the details for the user
          this.userService.updateUser(user);
          this.initPushNotification(user.uid);
          //This should only route if a deeplink is not routing
          if (this.nav.first() == null || this.nav.first().id == "welcome") {
            this.nav.setRoot('MyStuffPage');
          }
        } else if (this.nav.getActive() && this.nav.getActive().name == "WelcomePage") {
          console.log("already on welcomepage");
        }
        else {
          console.log('MyApp->WelcomePage');
          this.nav.setRoot('WelcomePage');
        }
      });
```

**Comment by RaphaelJenni** [comment]
Sry, I really don't know how to help with this problem.
Is there an error thrown?

**Comment by RaphaelJenni** [comment]
Close it because of inactivity.
