### ISSUE TITLE
How to Remove reCaptcha

### ISSUE THREAD

**Issue by KabalanKeirouz** [RaphaelJenni/FirebaseUI-Angular#110]
```
<ion-header>
  <ion-toolbar>
    <ion-title>
      Ionic Blank
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
  <firebase-ui></firebase-ui>

  <h1 *ngIf="afAuth.auth.currentUser">
    Welcome
  </h1>

  <ion-button *ngIf="afAuth.auth.currentUser" (click)="signOut()"
    >Sign Out</ion-button
  >
</ion-content>
```
The above code is the code in my home.page.html

```
import { Component } from "@angular/core";
import { AngularFireAuth } from "@angular/fire/auth";

@Component({
  selector: "app-home",
  templateUrl: "home.page.html",
  styleUrls: ["home.page.scss"]
})
export class HomePage {
  constructor(public afAuth: AngularFireAuth) {}

  signOut() {
    this.afAuth.auth.signOut().then(() => {
      location.reload();
    });
  }
}
```
The above code is the code in my home.page.ts

Created this project using Ionic 4 and FirebaseUI-Angular.
I would like to remove the reCaptcha so that my phone verification system works on IOS and to remove the error : 'ReaptchaVerifier is only supported in a browser HTTP/HTTPS environment'

**Comment by Konstantinos-Val** [comment]
I don't think you can remove reCaptcha when using the phone authentication provider. Firebase Auth docs state that clearly [read section 2 ](https://firebase.google.com/docs/auth/web/phone-auth)

> "Before you can sign in users with their phone numbers, you **must** set up Firebase's reCAPTCHA verifier. Firebase uses reCAPTCHA to prevent abuse, such as by ensuring that the phone number verification request comes from one of your app's allowed domains"

FirebaseUI-Angular is just a wrapper for FirebaseUI.

**Comment by KabalanKeirouz** [comment]
Oh okay thank you. Because I wanted to implement that on ionic 4 and use it on mobile but as it turned out, unfortunately it is not supported.

Thanks
