### ISSUE TITLE
Ionic+Cordova+FireBaseUI+Xcode (Cordova or Capacitor Build)

### ISSUE THREAD

**Issue by guntercn** [RaphaelJenni/FirebaseUI-Angular#112]
Hi
My work environment is

Ionic: 5.4.13
Cordova: 9.0.0

The final platform are( Android and IOS).

The Firebase settings of the app are according to the indications of the site.
In the Android version everything works fine.

I have a problem in the iOS version.

environment.ts
in this class assign the parameters for IOS.

When the application is running in the Simulator or in the App, an error shows up!

Error
RecaptchaVerifier is only supported in a browser HTTP/HTTPS enviroment

![image](https://user-images.githubusercontent.com/16024623/75925747-d8fa2480-5e2e-11ea-9a2c-11e487a6124a.png)

thanks

**Comment by choopage** [comment]
@guntercn  Isn't this a FirebaseUI problem. Not FirebaseUI-Angular problem? Because FirebaseUI-Angular is a wrapper for FirebaseUI.

**Comment by ihorbond** [comment]
@guntercn what did you end up doing ?

**Comment by RaphaelJenni** [comment]
Close due to inactivity
