### ISSUE TITLE
Help: change ui language and direction

### ISSUE THREAD

**Issue by NurdinDev** [RaphaelJenni/FirebaseUI-Angular#115]
I didn't find a good way to change the language of the UI, even the direction, it seems CDN way not working with angular wrapper, any other option can I use it with this wrapper? 

thanks in advance.

**Comment by choopage** [comment]
@NurdinDev  Can FirebaseUI can language of the UI? 
I am asking this because FirebaseUI-Angular is a wrapper of FirebaseUI https://github.com/firebase/firebaseui-web 

If FirebaseUI can't allow changing the UI, then should be a issue for FirebaseUI, in my opinion.

**Comment by RaphaelJenni** [comment]
Closed with the forked version of this wrapper.

Check the README section "i18n" or the PR #120 for more details.
