### ISSUE TITLE
ERROR in node_modules/firebaseui-angular/lib/firebaseui-angular-library.component.d.ts:17:9

### ISSUE THREAD

**Issue by himanshushankhala** [RaphaelJenni/FirebaseUI-Angular#119]
Command: **$   ionic serve -b -c**

Log: 

> ng run app:serve --host=localhost --port=8100
[ng] ℹ ｢wds｣: Project is running at http://localhost:8100/webpack-dev-server/
[ng] ℹ ｢wds｣: webpack output is served from /
[ng] ℹ ｢wds｣: 404s will fallback to //index.html
[ng] chunk {main} main.js, main.js.map (main) 2.02 kB [initial] [rendered]
[ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 154 kB [initial] [rendered]
[ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
[ng] chunk {styles} styles.js, styles.js.map (styles) 115 kB [initial] [rendered]
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 340 kB [initial] [rendered]
[ng] Date: 2020-03-28T20:16:06.650Z - Hash: 2b3cdbd6f96d11dde794 - Time: 5498ms
[ng] 
[ng] ERROR in node_modules/firebaseui-angular/lib/firebaseui-angular-library.component.d.ts:17:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 17     get firebaseUiConfig(): NativeFirebaseUIAuthConfig;
[ng]            ~~~~~~~~~~~~~~~~
[ng] 

[INFO] Development server running!
       
       Local: http://localhost:8100
       
       Use Ctrl+C to quit this process

[ng] ℹ ｢wdm｣: Failed to compile.

PACKAGE.JSON

"dependencies": {
    "@angular/common": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/fire": "^5.4.2",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@capacitor/core": "1.5.2",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "core-js": "^2.5.4",
    "firebase": "^7.13.1",
    "firebaseui": "^4.5.0",
    "firebaseui-angular": "^4.1.0",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.20",
    "@angular/cli": "~8.3.23",
    "@angular/compiler": "~8.2.14",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@capacitor/cli": "1.5.2",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
  "description": "An Ionic project"

**Comment by vyapariapp** [comment]
My error is this
`ERROR in node_modules/firebaseui-angular/lib/firebaseui-angular-library.component.d.ts(17,9): error TS1086: An accessor cannot be declared in an ambient context.`

**Comment by JohnnyK84** [comment]
Getting the same error as @himanshushankhala with a similar build in Ionic.
Strangely if you go to the file mentioned in the error and Ctrl S to re-save, the server will recompile successfully. Still doesn't fix the build issue though.

**Comment by housirvip** [comment]
```
"firebaseui-angular": "^4.1.0"
```
change to
```
"firebaseui-angular": "~4.0.1"
```

**Comment by nux17** [comment]
Same error within same context. Any updates?

**Comment by NikhilP97** [comment]
> ```
> "firebaseui-angular": "^4.1.0"
> ```
> 
> change to
> 
> ```
> "firebaseui-angular": "~4.0.1"
> ```

This worked for me, thanks @housirvip !

**Comment by ptorresmanque** [comment]
```
"firebaseui-angular": "^4.1.0",
"@angular/fire": "^6.0.2"
```
change to 
```
"firebaseui-angular": "~4.0.1",
"@angular/fire": "^5.0.0"
```

It only worked for me by changing this too

**Comment by choopage** [comment]
This works for me 

    "@angular/fire": "~5.2.1",
    "firebase": "^7.23.0",
    "firebaseui": "~4.7.1",
    "firebaseui-angular": "~4.0.1",

**Comment by RaphaelJenni** [comment]
Is this still an issue?
