### ISSUE TITLE
Ionic Android/IOS Deploy

### ISSUE THREAD

**Issue by techster10173** [RaphaelJenni/FirebaseUI-Angular#122]
If I were to deploy my ionic 4 app on android or ios will this library still work?

**Comment by RobinGiel** [comment]
@techster10173  yes

**Comment by techster10173** [comment]
@RobinGiel I have tested it on my app and it is rendering fine but it opens the Social Media Sign-on in the default browser and is not coming back to the app. Any idea of how to make it be taken care of in app?

**Comment by RobinGiel** [comment]
Every auth has it own way to redirect the app. You have to let the Google auth know that you need to redirect back to the app using the app domain. Also in firebase you can set this up at sign in methods

**Comment by techster10173** [comment]
@RobinGiel So I’d need to setup my application using deep links and connect that to the callback URL when sign in is successful?
