### ISSUE TITLE
Function calls are not supported in decorators but 'firebase' was called.

### ISSUE THREAD

**Issue by RDevR99** [RaphaelJenni/FirebaseUI-Angular#123]
I have this config: (Update: Doesn't show an error when Yahoo's provider Id is removed)
![image](https://user-images.githubusercontent.com/42928792/79300239-83369300-7f29-11ea-8623-7de3d81e83b2.png)

And am passing it in here in the App.module.ts imports array:
![image](https://user-images.githubusercontent.com/42928792/79300303-a3665200-7f29-11ea-873f-2ae5025c1c3b.png)

Now it runs fine with `ng serve` but fails during `ng build --prod`. 

the error looks like:
![image](https://user-images.githubusercontent.com/42928792/79300355-c7c22e80-7f29-11ea-8daa-d1db7013c23d.png)

**Comment by choopage** [comment]
@RahulRathodGitHub Can you create a https://stackblitz.com/ instant so that the error can be replicated? It's hard to figure out the error just with a few screenshot images without knowing the settings and code used.

**Comment by SamLuo835** [comment]
Having the same problem, any updtes?

**Comment by RaphaelJenni** [comment]
Is this still an issue? Are you sure, that this is not a problem with fireabseui itself?
Please provide more information, thanks.

**Comment by SamLuo835** [comment]
> Is this still an issue? Are you sure, that this is not a problem with fireabseui itself?
> Please provide more information, thanks.

In my case. I was using 5 login providers (Google, twitter, facebook, phone and apple). I had to remove the last two login methods and it worked in prod build

**Comment by RaphaelJenni** [comment]
This strongly sounds like a problem of firebaseui itself. The wrapper doesn't modify any of the provider data. Everything is passed directly to the firebaseui library. If the problem persist, please open an issue there.
