### ISSUE TITLE
One tap sign in with google doesn't work

### ISSUE THREAD

**Issue by mohamedaboelmagd** [RaphaelJenni/FirebaseUI-Angular#124]
I added this line to config
  `
credentialHelper: firebaseui.auth.CredentialHelper.GOOGLE_YOLO
`
nothing changes

**Comment by choopage** [comment]
I think FirebaseUI disabled GOOGLE_YOLO. Nothing to do with @RaphaelJenni wrapper.

**Comment by choopage** [comment]
I just tested. It didn't work. 
On a side note, they are deprecating YOLO for One-Tap in about a month.
So let's wait for FirebaseUI to update to the latest API.
https://github.com/firebase/firebaseui-web/issues/709

**Comment by RaphaelJenni** [comment]
Still an issue?

**Comment by choopage** [comment]
It was an issue. I believe it is because they deprecated YOLO.
