### ISSUE TITLE
Question: Did anyone successfully use EMAIL_LINK_SIGN_IN_METHOD in FirebaseUI-Angular

### ISSUE THREAD

**Issue by choopage** [RaphaelJenni/FirebaseUI-Angular#125]
Email and password sign-in without email link works.

However, I am having difficulty with Email and password sign-in with Email link verification.

It's stated in FirebaseUI that this is possible. https://github.com/firebase/firebaseui-web#email-link-authentication

@RaphaelJenni  Did you get email link verification working with your wrapper?

**Comment by RaphaelJenni** [comment]
@choopage Fist of all, thanks for helping me respond to the issues! You are a great help!

Regarding your question. I actually never tried it. I'm not actively using this wrapper in any project, just keeping the one here alive, to help others in need. But I will check if I find some time.

**Comment by choopage** [comment]
Thanks for your reply. Out of curiosity, if you aren't using this wrapper
how are you using Firebaseui web with Angular?

**Comment by RaphaelJenni** [comment]
I don't use firebaseui in any current project at all. When I use firebase auth, I most of the time add the functionality by myself, for design reasons.

But is this still an issue or can this one be closed?

**Comment by DustinJSilk** [comment]
I'm not able to get Email signup working with email links at all and I havent found anything on the Angular or UI issues.

(Thanks for all the hard work)
