### ISSUE TITLE
FirebaseUISignInFailure not being called

### ISSUE THREAD

**Issue by sunnylnct007** [RaphaelJenni/FirebaseUI-Angular#132]
Trying to use this library with Google provider. The login works fine. But if there is invalid user the pop up displays 403 error and doesn't do the  errorCallback. Possibly I am missing some config. The redirect_uri seems to be a potential issue but where do I pass that?
Even the change listener doesn't fireup in failure
Below is in my login component

```

--html
 <div>	
        <firebase-ui   (signInSuccessWithAuthResult)="successCallback($event)"
        (signInFailure)="errorCallback($event)" ></firebase-ui>
      
    </div>
--ts 

successCallback(signInSuccessData: FirebaseUISignInSuccessWithAuthResult)
  {
    console.log("called successfully")
    this.store.dispatch(authLogin());
    
  }
errorCallback(errorData: FirebaseUISignInFailure)
  {
    
    console.log("failed")
  }

```

Below is what I see in google pop up

Authorization Error
Error 403: access_denied
Request Details
hl=en
response_type=code
redirect_uri=https://test-1586615392127.firebaseapp.com/__/auth/handler

Happy to provide more input if needed.

Thansk for your help
Sunil

**Comment by RaphaelJenni** [comment]
Sorry for getting back to you so late. Is this still a problem?

**Comment by sunnylnct007** [comment]
Thanks for looking into it Raphael. It was a problem when I last tried it so I swithched to ngx-auth-firebaseui. 
You can close this issue if no one else has complained.
