### ISSUE TITLE
Request upgrade to support firebase sdk 8

### ISSUE THREAD

**Issue by mikedemarco** [RaphaelJenni/FirebaseUI-Angular#135]
I would like to use firebase sdk 8 in my project but I am blocked with compilation errors

```
ERROR in node_modules/firebaseui-angular/lib/firebaseui-angular-library.helper.d.ts:2:34 - error TS2694: Namespace '"/home/someapp/node_modules/firebase/index"' has no exported member 'auth'.
    
    2 import UserCredential = firebase.auth.UserCredential;
                                       ~~~~
    node_modules/firebaseui-angular/lib/firebaseui-angular-library.helper.d.ts:13:34 - error TS2694: Namespace '"/home/micydem/someapp/node_modules/firebase/index"' has no exported member 'auth'.
    
    13     credential: firebaseOriginal.auth.AuthCredential;
                                        ~~~~
```

It looks like firebase auth imports have changed [docs](https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/CHANGELOG.md)

**Comment by DaveA-W** [comment]
Note also breaking changes associated with @angular/fire 6.0.4 affect FirebaseUI-Angular too.
https://github.com/angular/angularfire/issues/2635

**Comment by RaphaelJenni** [comment]
I look into it ASAP

**Comment by RaphaelJenni** [comment]
Version 5.1.0 (https://www.npmjs.com/package/firebaseui-angular/v/5.1.0) is live with support for firebase 8.
Please give it a try and tell me if there are any porblems.

**Comment by aford22** [comment]
> Version 5.1.0 (https://www.npmjs.com/package/firebaseui-angular/v/5.1.0) is live with support for firebase 8.
> Please give it a try and tell me if there are any problems.

I have installed v5.1.0 in my Angular 10, Firebase 8 project. Installs, compiles and runs with no errors. Login UI works when signing in with email. Have not tried the other authentication methods yet. Will let you know.

**Comment by DaveA-W** [comment]
- [x]  Same successful result as @aford22. 
All good after upgrade to `angular*@10.2.2`, `firebaseui-angular@5.1.0`, `firebaseui@4.7.1`, `@angular/fire@6.0.5` and `firebase@8.0.1`

**Comment by mikedemarco** [comment]
Thanks for the quick updates @RaphaelJenni!

I can confirm everything is working with email and google sign-ins after upgrading using same versions as @DaveA-W   

Cheers!

**Comment by tigbeans** [comment]
Any plans to update this library to support firebase emulator authentication?

**Comment by RaphaelJenni** [comment]
@tigbeans Using the emulator is a firebase specific function (not firebaseui). As it seems, you can simply tell the firebase instance, that you want to connect to an emulator. (See: https://firebase.google.com/docs/emulator-suite/connect_auth#android_ios_and_web_sdks).

So I think, this is not functionality, that needs to be ported to this firebaseui wrapper. This might be something for angularfire.
