### ISSUE TITLE
Sample project missing CSS styles

### ISSUE THREAD

**Issue by tdkehoe** [RaphaelJenni/FirebaseUI-Angular#137]
In the sample project the file ```src/styles.scss``` needs one line: 

```
@import '~firebaseui/dist/firebaseui.css';
```

Looks much better with this dependency. :-)

**Comment by RaphaelJenni** [comment]
The firebaseui.css gets imported via the angular cli as described in "Add the firebaseui css to your imports" - Option 2 in the README.
