### ISSUE TITLE
Sample project could have README listing files that need to be changed

### ISSUE THREAD

**Issue by tdkehoe** [RaphaelJenni/FirebaseUI-Angular#138]
The sample project could have a README listing which files need to be changed: everything in /app except app.component.scss and app.component.spec.ts, plus index.html, styles.scss (see my other issue), and environments/environments.ts.

You could eliminate the ```index.html``` change by changing ``app.component.ts``` to ```selector: 'app-root',```.

**Comment by RaphaelJenni** [comment]
I don't understand what you mean. Can you create a PR with your proposed changes?
