### ISSUE TITLE
signInSuccess callback needed

### ISSUE THREAD

**Issue by amsamwalker** [RaphaelJenni/FirebaseUI-Angular#14]
We need this to retrieve the facebook access token.
credential.accessToken has that token when credential.providerId == 'facebook.com'

**Comment by RaphaelJenni** [comment]
I will check that in the following week.

**Comment by RaphaelJenni** [comment]
Fixed that:

V0.4.3
https://github.com/RaphaelJenni/FirebaseUI-Angular#signinsuccess-callback
