### ISSUE TITLE
UI disappears immediatly after login

### ISSUE THREAD

**Issue by KevinLourd** [RaphaelJenni/FirebaseUI-Angular#141]
Hi !

The UI disappears immediatly after login.

This is a design issue for me because the remaining of my landing page remains visible while waiting for post-login redirection

Would you know if there any any parameter to avoid disappearing when loggedin?

**Comment by RaphaelJenni** [comment]
This is the behavior of the [firebaseui-web](https://github.com/firebase/firebaseui-web) library. This wrapper does not change anything about that.
You would have to create an issue there.
