### ISSUE TITLE
Firebase Auth Emulator

### ISSUE THREAD

**Issue by EthanSK** [RaphaelJenni/FirebaseUI-Angular#142]
I can't get it to work with the firebase auth emulator? Help would be appreciated.

**Comment by AndreuRosellOsuna** [comment]
Me neither... :(

**Comment by AndreuRosellOsuna** [comment]
FirebaseUI-Angular is a wrapper of  angular-ui-web. And this library does not support auth emulator yet :
https://github.com/firebase/firebaseui-web/issues/778

It seems that some property on its dependency on firebase-js-sdk must be exposed to be called and consumed by firebaseui-web :
https://github.com/firebase/firebase-js-sdk/pull/4280

Once these two issues are resolved, I think firebaseui-angular-library-service.ts could get USE_EMULATOR injection token from @angular/fire/auth and use it to call useEmulator. I'm not an expert and I think that will be necessary but not enough...

Meanwhile, some guy suggests a hack just on angular-ui-web for dev purposes that enables emulator :
https://github.com/firebase/firebaseui-web/pull/794

**Comment by AndreuRosellOsuna** [comment]
firebase-js-sdk and firebaseui-web now are auth emulator compatible. I've created a pull request with the solution described above :
https://github.com/RaphaelJenni/FirebaseUI-Angular/pull/144

To use it, provide USE_EMULATOR provider from @angular/fire/auth :
```typescript
import {AngularFireAuthModule, USE_EMULATOR as USE_AUTH_EMULATOR} from '@angular/fire/auth';

...

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
 ....
  ],
  providers: [
    { provide: USE_AUTH_EMULATOR, useValue: !environment.production ? ['localhost', 9099] : undefined },
  ],
  bootstrap: [AppComponent]
})
`

Last versions from firebase and firebaseUI are required.

**Comment by AndreuRosellOsuna** [comment]
I pushed a package in npm with the fork :
https://www.npmjs.com/package/firebaseui-angular-auth-emulator-fork

**Comment by RaphaelJenni** [comment]
I'm looking into it.

**Comment by RaphaelJenni** [comment]
@AndreuRosellOsuna, thanks a lot for your PR! 
I checked it, made a few adjustments, and merged it.

Version 5.1.2 should be live in a moment.

Thanks for your help, I really appreciate it! :smiley:

**Comment by AndreuRosellOsuna** [comment]
Thanks to you for this library :)
