### ISSUE TITLE
Help: Inject configuration

### ISSUE THREAD

**Issue by gmaughan** [RaphaelJenni/FirebaseUI-Angular#146]
I need to be able to generate the `firebaseui.auth.Config` dynamically using configuration. This is because our clients can configure the application to enable different authentication providers.

Is there currently any way to do this?

If not, it would be great if I could inject the configuration using an injection token. Much like `@angular/fire` allows its configuration to be injected.

I could then use a provider factory (that reads from the app's configuration injection token) to build the firebaseui configuration object.

For example, this is what I do to configure `@angular/fire`:

```javascript
{
      // read firebase config from our config service
      provide: FIREBASE_OPTIONS,
      useFactory: (config: IConfig) => config.firebaseConfig,
      deps: [APP_CONFIG],
}
```

Where `APP_CONFIG` is our own injection token that holds our configuration object.

Thanks.
Glenn.

**Comment by gmaughan** [comment]
Sorry, I posted this in the wrong project. Should have been in FirebaseUI-Angular

**Comment by gmaughan** [comment]
Nope. I'm in the right place. Sorry about the noise.

**Comment by gmaughan** [comment]
Found a solution that seems to work but isn't documented.

I'm now bypassing the `forRoot()` call on the import and using:

```javascript
imports: [
    FirebaseUIModule
],
providers: [
    {
        provide 'firebaseUIAuthConfig',
        useFactory: (config: IConfig) => {
            const fbUiConfig: firebaseui.auth.Config = {
                signInFlow: 'redirect',
                signInOptions: [],
                tosUrl: null,
                privacyPolicyUrl: null,
                credentialHelper: firebaseui.auth.CredentialHelper.GOOGLE_YOLO
           };

           // conditionally construct the UI config based on our config
           if (config.googleAuth.enabled) {
                fbUiConfig.signInOptions.push(firebase.auth.GoogleAuthProvider.PROVIDER_ID);
           }

           return fbUiConfig;
       },
       deps: [APP_CONFIG]
    },
    {
      provide: 'firebaseUIAuthConfigFeature',
      useValue: {}
    }
}
```

As this is not documented, is this a reasonable way to do this?

Glenn.

**Comment by RaphaelJenni** [comment]
Hey Glenn @gmaughan 

To be honest, I never thought about this functionality. But it seems to be a clean way to do it like this. The `firebaseUIAuthConfigFeature` gets merged with the one provided in the `forRoot`, but if you provide all the necessary information, this should be fine too.

If this is done in your app module, you could also think about using `firebaseUIAuthConfig` instead of the `firebaseUIAuthConfigFeature`.


Would you mind creating a PR and updating the README with your findings and a description of how to achieve what you are aiming for?

**Comment by gmaughan** [comment]
Added #149

Sorry for the delay. It's been a busy period. #

**Comment by RaphaelJenni** [comment]
Thanks, I merged it,
