### ISSUE TITLE
l10n possible?

### ISSUE THREAD

**Issue by chiefmc** [RaphaelJenni/FirebaseUI-Angular#15]
Thanks for your work!

The only question I have if it is possible to get the localized version of the FirebaseUI?

**Comment by RaphaelJenni** [comment]
I will check that in the following week.

**Comment by RaphaelJenni** [comment]
Sadly at the moment, that's not possible. The localized version can only be [imported via the CDN](https://github.com/firebase/firebaseui-web#localized-widget). Here we use the npm module, so the option isn't available yet.

**Comment by Daaron3** [comment]
I'm pleased to announce that localized versions of the widget are available through the CDN.

**Comment by RaphaelJenni** [comment]
@Daaron3 what's the change? The CDN version was already available before...

**Comment by Daaron3** [comment]
Sorry my mistake, I accidentally changed npm for cdn...

**Comment by RaphaelJenni** [comment]
@Daaron3 where have you found that news? Haven't found an npm distribution
