### ISSUE TITLE
Compatibility with @angular/fire@^7.0.3

### ISSUE THREAD

**Issue by falk-stefan** [RaphaelJenni/FirebaseUI-Angular#158]
I tried to install the package but it seems it's not compatible with @angular/fire v7:

```
$ npm install firebaseui-angular --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: project@0.0.0
npm ERR! Found: @angular/fire@7.0.4
npm ERR! node_modules/@angular/fire
npm ERR!   @angular/fire@"^7.0.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/fire@"^6.0.0" from firebaseui-angular@5.1.3
npm ERR! node_modules/firebaseui-angular
npm ERR!   firebaseui-angular@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/sfalk/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sfalk/.npm/_logs/2021-09-12T12_20_41_818Z-debug.log
```

**Comment by RaphaelJenni** [comment]
@falk-stefan I created a beta version for the library (https://www.npmjs.com/package/firebaseui-angular/v/6.0.0-beta.0) that should work with @angular/fire@7 and firebase@9. Currently, the official firebaseui does not support firebase@9 in their release, but they have a `@next` version available (See the [Changelog](https://github.com/RaphaelJenni/FirebaseUI-Angular/blob/master/CHANGELOG.MD#600-beta0) for details).

Please let me know if you run into any problems.

**Comment by RaphaelJenni** [comment]
Version `6.0.0` (Angular 12) and Version `6.1.0` (Angular 13) are released.
See the README for the compatibility information.
