### ISSUE TITLE
This module will likely import firebase twice

### ISSUE THREAD

**Issue by code-tree** [RaphaelJenni/FirebaseUI-Angular#16]
I confess I haven't used this module, but I based my own code off it, and the way firebaseui is imported likely results in importing firebase twice, which can cause serious issues if the firebase modules are two different versions.

[Should not `import * as firebaseui from 'firebaseui'`](https://github.com/RaphaelJenni/FirebaseUI-Angular/blob/9e4e86c3e9b176c3085e194b2a5e87f629773f79/src/firebaseui.service.ts#L2)

[Instead follow procedure detailed here](https://github.com/firebase/firebaseui-web/issues/198#issuecomment-319865612)

**Comment by RaphaelJenni** [comment]
I will check that in the following week.

**Comment by RaphaelJenni** [comment]
Should it even be possible to have two different versions of firebase? If that's the case, an error would be the right thing...!?
Then in my code, I pass the auth instance of AngularFire to the firebaseUI module. That should prevent double initialization as well. ([Here](https://github.com/RaphaelJenni/FirebaseUI-Angular/blob/9e4e86c3e9b176c3085e194b2a5e87f629773f79/src/firebaseui.service.ts#L15))

Beside that, as you wrote in the firebaseui issue, to solve that, you would have to add the complete firebaseui code to your own, to remove that line where the import happens. And that code you would have to update every time the library gets an update too.

Correct me if I miss understood something.

**Comment by code-tree** [comment]
Hi @RaphaelJenni,

When I inspected the Firebase UI npm package files I discovered that `import ... from 'firebaseui'` pulls in a build of Firebase UI with filename `npm.js` which contains `require('firebase')`. You can see this in the [build code](https://github.com/firebase/firebaseui-web/blob/d839c18db390d00e974af21af896c1f551b98982/gulpfile.js#L37).

I'm not an expert on this, but from my understanding, Angular CLI pulls in the firebaseui's firebase version (located in firebaseui's own node_modules dir) because of that `require()` in addition to the firebase version that AngularFire uses (which may or may not be the same version). I assume this is because Firebase UI is not written in Typescript, so the compiler can't know that it wants the same module that AngularFire wants.

I then discovered that Firebase UI's npm package contains another built version that doesn't include the `require()` line, but looks for `firebase` on `window` instead. Hence my workaround, which puts AngularFire's firebase on `window`.

**Comment by code-tree** [comment]
> Then in my code, I pass the auth instance of AngularFire to the firebaseUI module. That should prevent double initialization as well.

I do this as well, but Firebase UI then takes a Credential object generated by AngularFire's firebase and gives it to methods of FirebaseUI's firebase (causing the errors I reported in the other issue).

**Comment by RaphaelJenni** [comment]
@code-tree Thanks for the explanation.

So you think I should import it like you did it in the other issue? Hasn't that any side effects?

**Comment by code-tree** [comment]
I think there must be a more elegant solution, but my mine seems to work fine at least. Only side effect is making `firebase` globally available on `window`.

**Comment by RaphaelJenni** [comment]
I think I have found a solution.
Instead of importing firebaseui manually, I just store the firebaseui instance on the window object.

**Comment by code-tree** [comment]
Ok, interesting. Seems like one way or another, something has to get attached to window then.

**Comment by RaphaelJenni** [comment]
Yeah, I think that issue is solved by that. I close it.
