### ISSUE TITLE
Update to support Angular 14

### ISSUE THREAD

**Issue by cupidchan** [RaphaelJenni/FirebaseUI-Angular#179]
Dependencies error starts throwing out after upgrading to Angular 14.0 We need to upgrade the dependencies to match up with the version.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: firebaseui-angular@6.1.1
npm ERR! Found: @angular/common@14.0.2
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.0.0" from the root project
npm ERR!   peer @angular/common@"^14.0.0 || ^15.0.0" from @angular/cdk@14.0.2
npm ERR!   node_modules/@angular/cdk
npm ERR!     @angular/cdk@"^14.0.0" from the root project
npm ERR!     peer @angular/cdk@"14.0.2" from @angular/material@14.0.2
npm ERR!     node_modules/@angular/material
npm ERR!       @angular/material@"^14.0.0" from the root project
npm ERR!       1 more (@angular/material-moment-adapter)
npm ERR!   7 more (@angular/fire, @angular/forms, @angular/material, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^6.1.2 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0" from firebaseui-angular@6.1.1
npm ERR! node_modules/firebaseui-angular
npm ERR!   firebaseui-angular@"^6.1.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/common@13.3.11
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^6.1.2 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0" from firebaseui-angular@6.1.1
npm ERR!   node_modules/firebaseui-angular
npm ERR!     firebaseui-angular@"^6.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by RaphaelJenni** [comment]
@cupidchan Sorry for the late reply, I'm currently a bit short on time.

I'll look into it ASAP.

**Comment by RaphaelJenni** [comment]
Version 6.1.2 with Angular 14 support is live.

**Comment by cupidchan** [comment]
Works perfectly now! Thanks @RaphaelJenni!
