### ISSUE TITLE
Where do I import FirebaseUISignInSuccess from?

### ISSUE THREAD

**Issue by patricknasc** [RaphaelJenni/FirebaseUI-Angular#18]
In the provided example:

successCallback(signInSuccessData: FirebaseUISignInSuccess) {
    ...
}

Where do I import FirebaseUISignInSuccess from?

**Comment by RaphaelJenni** [comment]
It is called by an event
[Docs](https://github.com/RaphaelJenni/FirebaseUI-Angular#signinsuccess-callback)

**Comment by sksvenson** [comment]
import { FirebaseUISignInSuccess } from 'firebaseui-angular';

**Comment by RaphaelJenni** [comment]
Ah sorry. Look at @sksvenson answer
