### ISSUE TITLE
Integrate project into Angular 16

### ISSUE THREAD

**Issue by jzabinski-dolios** [RaphaelJenni/FirebaseUI-Angular#199]
Now that Angular 16 is released, it would be great if this project could use it [as a peer](https://github.com/RaphaelJenni/FirebaseUI-Angular/blob/36d4546e9e8aeb935e226f221a6e8504778b34bc/projects/firebaseui-angular-library/package.json#L24).

**Comment by moblizeitllc** [comment]
i need it as well for angular 16

**Comment by RaphaelJenni** [comment]
I'm currently a bit low on time. It is on my todo list, but I cannot give any timeframe. If it is urgent, feel free to create a PR.
