### ISSUE TITLE
Angular 18 compatibility

### ISSUE THREAD

**Issue by mbimbij** [RaphaelJenni/FirebaseUI-Angular#209]
Any ETA for compatibility with the lastest release of Angular ? I tried a week or 2 ago, it failed and i reverted to Angular 17. I no longer have the error message at hand but i could get it back if you want.

Best regards

**Comment by edicon** [comment]
See link below for Angular v18. It works fine on v18.
https://github.com/RaphaelJenni/FirebaseUI-Angular/blob/master/src/main.ts

**Comment by RaphaelJenni** [comment]
Added in release 6.3.0
