### ISSUE TITLE
Running with ionic 3/angular 4

### ISSUE THREAD

**Issue by stansongman** [RaphaelJenni/FirebaseUI-Angular#21]
Hello, I started integrating FirebaseUI-Angular into my ionic 3/angular 4 app.  It was very straightforward, although the formatting is not working properly as you can see.  I link to the .css file from within index.html, and that should work. 

![screen shot 2017-09-27 at 1 44 26 pm](https://user-images.githubusercontent.com/22638931/30928683-3dac22e6-a38a-11e7-9764-37f910fb7483.png)

Any idea what might be going wrong?  This is pretty much a cut and paste from the sample program.

**Comment by GuateDevIO** [comment]
I face the same issue before and it was fixed after I added the firebaseui css to your imports:

Angular-CLI

File: .angular-cli.json

Path: "../node_modules/firebaseui/dist/firebaseui.css"

{
"apps": [
    {
      ...
      "styles": [
        "styles.css",
        "../node_modules/firebaseui/dist/firebaseui.css"
      ],
      "scripts": [],
      ...
    }
  ]
}

**Comment by RaphaelJenni** [comment]
As GuateDevIO said add the css in the angular-cli file as described here (same part he coppied here): https://github.com/RaphaelJenni/FirebaseUI-Angular/blob/master/README.MD#how-to-use

**Comment by stansongman** [comment]
Thanks for the quick response.  I had done that, but debugging in Chrome I notice I’m getting a 404.  Where do you put .angular-cli.json into?  I have it in the root of my ionic project.

Thanks,
-s-

Stan Swiniarski
CEO and Co-founder
iPayMyWay, Inc.
sswiniarski@ipaymyway.com<mailto:sswiniarski@ipaymyway.com>
http://www.ipaymyway.com
m: 978.337.9017


[cid:F43058CA-28CD-4B67-BB52-FD88DC17F801]

On Sep 28, 2017, at 1:35 AM, Raphael Jenni <notifications@github.com<mailto:notifications@github.com>> wrote:


As GuateDevIO said add the css in the angular-cli file as described here (same part he coppied here): https://github.com/RaphaelJenni/FirebaseUI-Angular/blob/master/README.MD#how-to-use

**Comment by RaphaelJenni** [comment]
Well, have you added the angular-cli by your self or was it generated in the beginning? Can you provide a sample project?

**Comment by RaphaelJenni** [comment]
Were you able to solve this issue?

**Comment by stansongman** [comment]
Sorry, I got pulled off onto other things.  It's an issue with getting ionic 3 to include css files from node_modules folders.  Here's an approach I'll be trying:  https://stackoverflow.com/questions/40943914/how-do-i-include-javascriptcss-from-node-modules-in-ionic-2

**Comment by RaphaelJenni** [comment]
Any luck? If yes I would like to close this issue.

**Comment by powercover** [comment]
@stansongman its easy with **ionic3**

1. Create folder **config** under root directory
2. Create file called **copy.config.js** with code:
`module.exports = {
  copyFirebaseUiCss: {
    src: ['./node_modules/firebaseui/dist/firebaseui.css'],
    dest: '{{BUILD}}'
  }
}`
3. Next modify **package.json** and insert
`"ionic_copy": "./config/copy.config.js"` inside **config** object
4. Add `<link href="build/firebaseui.css" rel="stylesheet">`
after `<link href="build/main.css" rel="stylesheet">` inside **index.html**
