### ISSUE TITLE
Sample doesn't compile

### ISSUE THREAD

**Issue by keith-nativemobile** [RaphaelJenni/FirebaseUI-Angular#22]
Trying to run the current sample code I see:
firebaseui-angular"' has no exported member 'CredentialHelper'

I presume this is caused by the dependency "firebaseui-angular": "0.4.2" .

Experimenting with the dependencies I found that the following combination works:

    "angularfire2": "^5.0.0-rc.1",
    "core-js": "^2.4.1",
    "firebase": "^4.5.0",
    "firebaseui": "^2.2.1",
    "firebaseui-angular": "0.4.5",

**Comment by RaphaelJenni** [comment]
I will check that in the following days.

**Comment by RaphaelJenni** [comment]
I need to update the plugin's dependencies. Will do that now.

**Comment by RaphaelJenni** [comment]
Updated the plugin/sample and adjusted the plugin version to the firebaseui version. So version 2.4.0 is live now.
