### ISSUE TITLE
Login in progress

### ISSUE THREAD

**Issue by aleixsuau** [RaphaelJenni/FirebaseUI-Angular#23]
Hi Raphael,
Thank you for your library.
One question: ¿Is there any way to know when the login action is in progress? I'd like to show a custom spinner...
I see that they add/remove an element with the class ".firebaseui-callback-indicator-container" while it's login but I can't find the mechanism.
Thanks!

**Comment by RaphaelJenni** [comment]
So do I understand correct: You open the login process in a popup and want to show a spinner during the time the login process is running?

**Comment by aleixsuau** [comment]
Hi @RaphaelJenni , 
I'm doing a redirection instead of the pop up, but yes, that is it. 
Right now I'm able to know when the user auth state changes (AngularFireAuth.authState) but I'd like to know when the auth action starts and ends.
Thanks!

**Comment by RaphaelJenni** [comment]
But if you have the redirect, the page isn't shown anyway, so no need for a loading indicator. Or do I understand something wrong?

**Comment by aleixsuau** [comment]
When the redirect is done (the user is back in the app), authentification is still in process. In fact, the firebaseUI shows an spinner.
The thing is that I have the firebaseUI widget in a hover:menu and I want to keep it visible while the login is in progress. Then hide it when the auth is done.

**Comment by RaphaelJenni** [comment]
I will close that because of inactivity.

If this still is an issue you could try to use the callback to close it. It that doesn't work for you, feel free to reopen this issue.
