### ISSUE TITLE
signOutSuccess callback needed

### ISSUE THREAD

**Issue by ishandutta2007** [RaphaelJenni/FirebaseUI-Angular#26]
On lines of https://github.com/RaphaelJenni/FirebaseUI-Angular/issues/14
I need to reset my user object in browser, signOutSuccess callback seems to be the best non-hackish approach but we dont have it yet.

**Comment by RaphaelJenni** [comment]
I will do that as soon as possible. But I'm also open for PR's.

**Comment by praveeno** [comment]
Let me know, how can i help

**Comment by RaphaelJenni** [comment]
Sorry, it went under...
@praveeno You can implement that functionality and create a PR for that.

**Comment by RaphaelJenni** [comment]
I will look into that together with #45

**Comment by RaphaelJenni** [comment]
Hello @ishandutta2007 
Sorry, that it took so long.

To get the sign out callback, you should use AngularFire, as this project is just a wrapper around the official one. If they implement a callback like that, I will integrate it as well,
