### ISSUE TITLE
feat: Integrates one-tap sign-up

### ISSUE THREAD

**Issue by choopage** [RaphaelJenni/FirebaseUI-Angular#27]
Integrates one-tap sign-up with FirebaseUI-web: https://developers.google.com/identity/one-tap/web/overview

Available with v2.5 of FirebaseUI-web https://github.com/firebase/firebaseui-web/releases

**Comment by RaphaelJenni** [comment]
It's already integtated in the newest version. But haven't updated the README yet. I will do that in the coming days.

**Comment by RaphaelJenni** [comment]
Done with: f17455829151358a84f05abc146f27942bf3ee8d
