### ISSUE TITLE
please remove line `import rxjs/Rx' from index.js which is unused but may cause some problems. 

### ISSUE THREAD

**Issue by johnking** [RaphaelJenni/FirebaseUI-Angular#28]
Hi @RaphaelJenni,
First of all, thanks a lot for your package and it saved me lot of time to develop my own. 

I was struggling to troubleshooting an error occurred in this package after upgrading other packages, similar to [ERROR in ./node_modules/rxjs/_esm5/observable/BoundNodeCallbackObservable.js](https://github.com/angular/angular/issues/20095)  

After commenting out the line `import 'rxjs/Rx'` from file index.js, the issue disappears.  

There are also some recommendations on how to import ` rxjs/Rx` from the thread to avoid such issues.

thanks again and Best regards

-John

**Comment by RaphaelJenni** [comment]
I will do that ASAP

**Comment by johnking** [comment]
thanks Raphael!

**Comment by RaphaelJenni** [comment]
Fixed in `v2.5.2`.

**Comment by johnking** [comment]
Thanks!
