### ISSUE TITLE
Firebase 4.8.1 was refactored... imports now from @firebase

### ISSUE THREAD

**Issue by randroid88** [RaphaelJenni/FirebaseUI-Angular#29]
See this issue which is affecting FirebaseUI-Angular:
https://github.com/firebase/firebase-js-sdk/issues/388

**Comment by RaphaelJenni** [comment]
I will do that ASAP.

**Comment by RaphaelJenni** [comment]
I updated the plugin dependencies, but angularfire2 has the same problem. Have to wait to be fixed by them.
