### ISSUE TITLE
Invoke phone login screen for unauthorized user

### ISSUE THREAD

**Issue by kshkrao3** [RaphaelJenni/FirebaseUI-Angular#35]
Probably this is a question/feature request [if unavailable]

I am building an e-commerce application and when an unauthorized user is about checkout any item purchased, I would like to authorize him with the phone number he entered [phone number is mandatory], with which I can also assure that he is a valid user. 

Is it possible to invoke phone auth specifically on some action with the phone number prefilled?

**Comment by RaphaelJenni** [comment]
According to this docs you can prefil the phone numebr: https://stackoverflow.com/questions/48681631/firebaseui-js-uncaught-typeerror-cannot-read-property-call-of-undefined#

To invoke it only on user action you can use ngIf on the component and only show it if it should. (That's the current state). If you have something different in mind feel free to comment it here or create a PR.

**Comment by kshkrao3** [comment]
@RaphaelJenni The link for doc you provided is the same you posted on #34. Is that right? 

ngIf should be used on the complete component? I mean on `<firebase-ui></firebase-ui>`? Should I use phone login method separately and add `<firebase-ui></firebase-ui>`? Bit confused here? Can we configure/prefil number on go?

**Comment by RaphaelJenni** [comment]
I updated the link.
I haven't worked with phone auth yet... have to look into it at some point.

**Comment by kshkrao3** [comment]
@RaphaelJenni Surely. Please let me know if you have any upgrades on this.. :)

**Comment by RaphaelJenni** [comment]
@kshkrao3 have you found a solution for that?

**Comment by kshkrao3** [comment]
@RaphaelJenni Not really, but I changed it to be a general way of logging in so that user has to be authorized before he can checkout.

**Comment by kshkrao3** [comment]
That's fine @RaphaelJenni. We can close this for now..
