### ISSUE TITLE
OneTap doesn't work

### ISSUE THREAD

**Issue by ribrdb** [RaphaelJenni/FirebaseUI-Angular#36]
If I change the sample app to use AuthMethods.Redirect and CredentialHelper.OneTap, there is an uncaught exception after signing in. I tried logging in with both Google and Facebook providers, but they both have the exception.

**Comment by RaphaelJenni** [comment]
How have you configured the oneTap option?

**Comment by ribrdb** [comment]
Actually it appears this is a bug in FirebaseUI 2.6.x, if I switch back to 2.5.1 it works.
