### ISSUE TITLE
Auth stopped working after updating to latest dependencies

### ISSUE THREAD

**Issue by matiishyn** [RaphaelJenni/FirebaseUI-Angular#37]
This used to work fine but stopped working after updating dependencies.
Currently I'm investigating what causes the problem,
but here's what I get:
video here http://recordit.co/vMDm8Wj3Y8
![image](https://user-images.githubusercontent.com/3661065/36719662-5b65c41c-1bae-11e8-8314-a63603f8b90d.png)

The error (`signInWithCredential failed: First argument "credential" must be a valid credential.`) happens for both `AccountChooser` and `OneTap` CredentialHelpers.

My set up is pretty simple:
```ts
export const firebaseUiAuthConfig: FirebaseUIAuthConfig = {
  providers: [
    // googleCustomConfig,
    AuthProvider.Google,
    AuthProvider.Facebook,
    AuthProvider.Password,
    AuthProvider.Phone
  ],
  method: AuthMethods.Popup,
  credentialHelper: CredentialHelper.AccountChooser
};
....
FirebaseUIModule.forRoot(firebaseUiAuthConfig),
``` 

and dependencies:
```json
"dependencies": {
    ...
    "@angular/common": "^5.2.6",
    "@angular/compiler": "^5.2.6",
    "@angular/core": "^5.2.6",
    ...
    "angularfire2": "^5.0.0-rc.6",
    "firebase": "^4.10.1",
    "firebaseui": "^2.6.1",
    "firebaseui-angular": "^2.6.1",
    ...
  },
```
Does anyone have something similar?

**Comment by RaphaelJenni** [comment]
I have to check that. In the release notes they mentioned something about an api change.

**Comment by RaphaelJenni** [comment]
I don't have this problem. And can't reproduce it. Same versions as you have. How did you update? Maybe there is a version mismatch. You can try to delete the `node_modules` and the `package-lock.json` and run npm install. Maybe this will solve the issue.

**Comment by stevebrowndotco** [comment]
I can confirm I am getting the same issue.

**Comment by matiishyn** [comment]
good
well, not good that you get you
but good that I'm not the only one getting this.

I tried to revert `firebaseui` to some older versions but it didn't help.

**Comment by stevebrowndotco** [comment]
Please let me know if you fix it! I am also debugging

**Comment by matiishyn** [comment]
reverting `firebase` to `"firebase": "4.10.0",` helped.
It causes another error, 
but at least it works :)

![image](https://user-images.githubusercontent.com/3661065/36745426-1daa580a-1bf8-11e8-901c-1c40e5587cfe.png)

**Comment by RaphaelJenni** [comment]
Yes, this is a known issue, but not resolved yet.

**Comment by stevebrowndotco** [comment]
I can confirm that the downgrading to the following versions fix the issue:

```
        "firebase": "^4.10.1",
        "firebaseui": "2.5.1",
        "firebaseui-angular": "2.5.0",
        "angularfire2": "^5.0.0-rc.6",
```

@RaphaelJenni  It looks like the bug occurs after firebaseui 2.5.1.

@matiishyn note that I can use firebase 4.10.1.

**Comment by RaphaelJenni** [comment]
Installed the newest versions. No errors for me anymore. Can you verify if the problem is solved?

Dependencies of the sample project:
```
"dependencies": {
    "@angular/common": "^5.2.9",
    "@angular/compiler": "^5.2.9",
    "@angular/core": "^5.2.9",
    "@angular/forms": "^5.2.9",
    "@angular/http": "^5.2.9",
    "@angular/platform-browser": "^5.2.9",
    "@angular/platform-browser-dynamic": "^5.2.9",
    "@angular/router": "^5.2.9",
    "@types/firebase": "^3.2.1",
    "angularfire2": "^5.0.0-rc.5-next",
    "core-js": "^2.5.3",
    "firebase": "^4.11.0",
    "firebaseui": "^2.6.3",
    "firebaseui-angular": "^2.6.1",
    "promise-polyfill": "6.0.2",
    "rxjs": "^5.5.7",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "^1.7.3",
    "@angular/compiler-cli": "^5.2.9",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.102",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "^1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "2.6.2"
  }
```
