### ISSUE TITLE
requireDisplayName: false

### ISSUE THREAD

**Issue by pashaseliverstov** [RaphaelJenni/FirebaseUI-Angular#38]
How to configure requireDisplayName with firebaseUiAuthConfig?
signInOptions: [
        {
          provider: firebase.auth.EmailAuthProvider.PROVIDER_ID,
          requireDisplayName: false
        }
      ]

**Comment by RaphaelJenni** [comment]
Sorry, I have missed this issue.

It should work like that, but I'm not sure if it is implemented correctly. I will check it and inform you about the result.
```
const passwordCustomConfig: AuthProviderWithCustomConfig = {
  provider: AuthProvider.Password,
    customParameters: {
      requireDisplayName: false
    }
  }
};
```

**Comment by RaphaelJenni** [comment]
@pashaseliverstov Checked it. It works.

**Comment by nexant-ienergy** [comment]
Thank you!. Could you please release version 2.6.2

**Comment by nexant-ienergy** [comment]
![image](https://user-images.githubusercontent.com/4432097/38344129-b08b29aa-383c-11e8-934c-bf5d3f30c054.png)

**Comment by RaphaelJenni** [comment]
Ah yeah sorry, will add it to the github releases. Stil getting used to that.
