### ISSUE TITLE
Q: Localised Widget?

### ISSUE THREAD

**Issue by RancLoucka1** [RaphaelJenni/FirebaseUI-Angular#39]
Hi, any idea on how to make this localised? I would like to show the contents in Czech language preferably. I am aware that there is an localised widget for FirebaseUI for inline insertion through <script> tag, however, that does not seem to apply for NPM modules or Angular CLI. I guess I could clone and rebuild the original FirebaseUI with localised data and somehow make FirebaseUI-Angular use it, but I am not really sure how exactly and I am afraid that it will make later updates on the package bit more messy. Any suggestions please?

**Comment by RaphaelJenni** [comment]
Currently it the npm package isn't supported. The option that you build the package yourself is possible, you just need to replace the original firebase plugin with your own version, FirebaseUI-Angular shouldn't be affected by that.
The problem of updates can't be solved right now. You can create a script, which would clone the newest version from GitHub and build the plugin in the desired language. This version could that be published to npm and used in your app.

As soon as I know of any new way, I will update the docs and/or the plugin.

**Comment by RancLoucka1** [comment]
Thanks RaphaelJenni. This is unfortunate, but the ball is at the Google's side I guess. I will try to rebuild the FurebaseUI then ...
