### ISSUE TITLE
../firebaseUI-Angular  has no exported member 'AuthProviders'

### ISSUE THREAD

**Issue by apurva304** [RaphaelJenni/FirebaseUI-Angular#4]
I'm getting this error.
Angular fire version 4.0.0-rc.0
<img width="703" alt="capture" src="https://cloud.githubusercontent.com/assets/14852030/26120054/11432b5c-3a8d-11e7-9bee-f8f391fed9dd.PNG">

Going through the code in the .../node_modules/firebaseUI-Angular , I found out that the code here at the repository is different. So I tried to update the packages with npm update.

Even Reinstalling the package with npm install firebaseUI-Angular --save  doesn't download the new version of the package

**Comment by RaphaelJenni** [comment]
I have to check that. Maybe the npm build didn't work.

**Comment by RaphaelJenni** [comment]
So I checked that. I don't have this problem. But "AngularFire" has been removed and replaced with AngularFireModule, AngularFireDatabaseModule, AngularFireAuthModule. So corresponding to your Error it is looking for this import but can't find it.

You can read more about that in the migration doc of AngularFire2:
https://github.com/angular/angularfire2/blob/master/docs/version-4-upgrade.md

I hope that helps. If you have any further question, ask here. 😄
