### ISSUE TITLE
"method" default not working

### ISSUE THREAD

**Issue by IlCallo** [RaphaelJenni/FirebaseUI-Angular#40]
In the docs it's written that the "method" option of the configuration is optional and that "AuthMethods.Popup" will be used is none is specified.
I tried using the package with minimal configuration (only "providers" array and only Password provider) and Angular complained about needing the "method" option.

If I set that option, it works just fine.

**Comment by RaphaelJenni** [comment]
Oh, I will look into it ASAP.

**Comment by RaphaelJenni** [comment]
Version 2.6.2 live now. Should be fixed.
