### ISSUE TITLE
Fails when built for production with build-optimizer=true

### ISSUE THREAD

**Issue by keith-nativemobile** [RaphaelJenni/FirebaseUI-Angular#41]
We just upgraded from Angular 4 to 5. Sign in with Google, Facebook etc work in dev mode but when building for production with the --prod flag, the app crashes with the exception "Cannot read property 'GoogleAuthProvider' of undefined:"

![screen shot 2018-03-23 at 3 05 11 pm](https://user-images.githubusercontent.com/16183849/37807721-c8309c88-2eab-11e8-807f-1aaf85cfcad1.png)

If I build with --prod --aot=true --build-optimizer=false then no exception is generated

**Comment by RaphaelJenni** [comment]
I will look into it this weekend.

**Comment by RaphaelJenni** [comment]
No problem for me...

![image](https://user-images.githubusercontent.com/14369284/37863507-54581a2a-2f5f-11e8-82b4-04dcb3d389f9.png)

**Comment by RaphaelJenni** [comment]
@keith-nativemobile Any news on your side?

**Comment by RaphaelJenni** [comment]
Close due to inactivity.
