### ISSUE TITLE
Error: firebaseui-angular.d.ts, found version 4, expected 3

### ISSUE THREAD

**Issue by praveeno** [RaphaelJenni/FirebaseUI-Angular#43]
Hello, 
Recently I update dependencies, and afterwards getting error
 
![image](https://user-images.githubusercontent.com/19618730/39392194-586e18cc-4acf-11e8-9043-ff62fd6c4d48.png)

depedency version
![image](https://user-images.githubusercontent.com/19618730/39392200-7853860e-4acf-11e8-8b13-62ec331586d7.png)

let me know, how to solve this.

**Comment by RaphaelJenni** [comment]
@praveeno Have you tried to delete the node_modules folder and run `npm install` again?

**Comment by praveeno** [comment]
Yes, I done that, still getting same error

**Comment by RaphaelJenni** [comment]
Can you try to update your dependencies to this versions:

```
"angularfire2": "^5.0.0-rc.6",
"firebase": "4.11.0", // Fix this version, due to a angularfire bug
"firebaseui": "^2.7.0",
"firebaseui-angular": "^2.6.2",
```

**Comment by praveeno** [comment]
I'll  try this also, after see a stackoverflow answer, but it also not help

**Comment by RaphaelJenni** [comment]
Which version of angular do you use?

**Comment by RaphaelJenni** [comment]
Version 3.0.0 is out now.
