### ISSUE TITLE
TypeError: Cannot read property 'GoogleAuthProvider' of undefined

### ISSUE THREAD

**Issue by kingkassem** [RaphaelJenni/FirebaseUI-Angular#44]
webpack-internal:///../../../../firebaseui-angular/index.js:103 Uncaught TypeError: Cannot read property 'GoogleAuthProvider' of undefined
    at eval (webpack-internal:///../../../../firebaseui-angular/index.js:103)
    at Object.../../../../firebaseui-angular/index.js (vendor.bundle.js:3279)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (webpack-internal:///../../../../../src/app/app.module.ts:12)
    at Object.../../../../../src/app/app.module.ts (main.bundle.js:44)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (webpack-internal:///../../../../../src/app/index.ts:3)
    at Object.../../../../../src/app/index.ts (main.bundle.js:304)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (webpack-internal:///../../../../../src/main.ts:6)

dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/cdk": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/platform-server": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@firebase/app": "^0.1.6",
    "angularfire2": "^5.0.0-rc.6.0",
    "firebase": "^4.13.1",
    "firebaseui": "^2.7.0",
    "firebaseui-angular": "^2.6.2",
      ....
  },

**Comment by RaphaelJenni** [comment]
Please provide some more details.

**Comment by kingkassem** [comment]
os: windows 10
Google Chrome Version 66.0.3359.139 (Official Build) (64-bit)
i tried to down grade to older firebase and firebaseui but the same error

i don't know why this problem

**Comment by RaphaelJenni** [comment]
Have you tried the sample app of this repo?

**Comment by kingkassem** [comment]
yes, and it works fine

**Comment by kingkassem** [comment]
ok , i will try

**Comment by kingkassem** [comment]
after remove node_modules folder and run npm i again and upgrade angularfire it works without this error 
but the component didn't rendered and the page is empty although i found it in the chrome dev tools ??

**Comment by RaphaelJenni** [comment]
Any errors?

**Comment by kingkassem** [comment]
no errors, when i ng new Project and install it with angluarfire@next same thing nothing appears

although when i use it with angular 6 beta it works as required !!!

**Comment by ih57452** [comment]
I was getting the same error using firebase@4.13. I downgraded to 4.12 and it works again.

**Comment by kingkassem** [comment]
@ih57452 what is the version for angularfire2 , firebaseui,  firebaseui-angular you use.

**Comment by ih57452** [comment]
I'm using the latest version of everything else; the same versions you have in your first post.

**Comment by kingkassem** [comment]
thanks alot now it works
