### ISSUE TITLE
Support firebase-ui 3.0

### ISSUE THREAD

**Issue by keith-nativemobile** [RaphaelJenni/FirebaseUI-Angular#49]
I checked out version 2.6.2 and confirmed that the sample ran as expected. I then updated the sample project to use firebase 5.0.2, angualrfire 5.0.0-rc.7 and firebaseui v3.0.0.

 I see this warning:

[WDS] Warnings while compiling.
index.js:147
./node_modules/firebaseui-angular/index.js
index.js:153
87:25-31 "export 'auth' (imported as 'auth$2') was not found in 'firebase/app'
 @ ./node_modules/firebaseui-angular/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:0 ./src/main.ts
./node_modules/firebaseui-angular/index.js

I then hit this exception:

TypeError: Cannot read property 'GoogleAuthProvider' of undefined
index.js:87
    at eval (/Users/keithcoughtrey/NativeMobile/Trove/FirebaseUI-Angular/sample/node_modules/firebaseui-angular/index.js:87:1)
    at Object../node_modules/firebaseui-angular/index.js (http://localhost:4200/vendor.bundle.js:204:1)

**Comment by RaphaelJenni** [comment]
This issue already exists in #47

**Comment by RaphaelJenni** [comment]
Version 3.0.0 is out now.
