### ISSUE TITLE
after first login. firebase-ui empty until page is refreshed

### ISSUE THREAD

**Issue by nikmartin** [RaphaelJenni/FirebaseUI-Angular#5]
If I load my angular2 app and click the sign in modal that contains `<firebase-ui >`, I'm able to login in with any of the providers I've configured. Once this happens, all subsequent attemps to display the login dialog display: 
`<firebase-ui ><div id="firebaseui-auth-container"></div></firebase-ui>`
The container is empty, and only doing a hard refresh of the page will display them again, regardless of logged in state.

**Comment by RaphaelJenni** [comment]
I checked it and I have the same problem too. Must happend in the upgrade to angularfire2 4.0.
I will fix that asap.

**Comment by RaphaelJenni** [comment]
Fixed it and upgraded firebase/firebaseui to the newset version.
Give it a try and let me know if it worked.

**Comment by nikmartin** [comment]
It does appear to be fixed, thanks!
