### ISSUE TITLE
This package uses a development build of Firebase.

### ISSUE THREAD

**Issue by kdubau** [RaphaelJenni/FirebaseUI-Angular#50]
Warning produced under latest firebase/angular: 
```It looks like you're using the development build of the Firebase JS SDK.
When deploying Firebase apps to production, it is advisable to only import
the individual SDK components you intend to use.

For the module builds, these are available in the following manner
(replace <PACKAGE> with the name of a component - i.e. auth, database, etc):

CommonJS Modules:
const firebase = require('firebase/app');
require('firebase/<PACKAGE>');

ES Modules:
import firebase from 'firebase/app';
import 'firebase/<PACKAGE>';
```

I believe the issue is here: https://github.com/RaphaelJenni/FirebaseUI-Angular/blob/master/projects/firebaseui-angular-library/src/lib/firebaseui-angular-library.component.ts#L9

And I think the fix is changing that line to simply: `import * as firebase from 'firebase/app';` but then you'll also need to include the auth module: `import 'firebase/auth';`.

I'm not sure how to best test the change, else I would PR myself.

Thanks.

**Comment by RaphaelJenni** [comment]
Hey
I'm aware of that. Currently, there are some incompatibilities going on with all the different firebase plugins. I'm working on a fix, which should include this issue as well.

**Comment by RaphaelJenni** [comment]
Version 3.0.0 is out now.
