### ISSUE TITLE
doc: Provide upgrading of anonymous users

### ISSUE THREAD

**Issue by choopage** [RaphaelJenni/FirebaseUI-Angular#53]
How to provide upgrading of anonymous users? It is a feature available in Firebase Web UI. https://github.com/firebase/firebaseui-web#upgrading-anonymous-users

**Comment by RaphaelJenni** [comment]
Sorry, missed that. Will do that ASAP.

**Comment by RaphaelJenni** [comment]
Fixed in 3.0.1

**Comment by choopage** [comment]
hi @RaphaelJenni thanks for fixing this. May I know how to go about using upgrading anonymous users with your library? Do you have brief documentation on this.

**Comment by RaphaelJenni** [comment]
Is documented in the ReadMe: https://github.com/RaphaelJenni/FirebaseUI-Angular/blob/master/README.MD#config

**Comment by choopage** [comment]
@RaphaelJenni When using upgrade anonymous, it needs to use this method signInFailure https://github.com/firebase/firebaseui-web#signinfailureerror which is mentioned https://github.com/firebase/firebaseui-web#handling-anonymous-user-upgrade-merge-conflicts 

Could you expose `signInFailure()` method?

**Comment by RaphaelJenni** [comment]
Fixed in 3.0.2

**Comment by choopage** [comment]
@RaphaelJenni could you accept this PR. Many thanks.

**Comment by RaphaelJenni** [comment]
Thanks for the PR. I will check it this evening.
