### ISSUE TITLE
question: Is your OneTap working in dev. environment?

### ISSUE THREAD

**Issue by choopage** [RaphaelJenni/FirebaseUI-Angular#54]
My OneTap is not working in my localhost environment. Is yours working? 
It could have been my setting misconfigured. 
My only configuration is 

```
import {
  AuthMethods, AuthProvider, CredentialHelper,
  FirebaseUIAuthConfig
} from 'firebaseui-angular';

export const FirebaseUiAuthConfig: FirebaseUIAuthConfig = {
  providers: [
    AuthProvider.Google,
    AuthProvider.Password
  ],
  method: AuthMethods.Popup,
  credentialHelper: CredentialHelper.OneTap // this is the only configuration I set from None to OneTap
};
```

*note: In localhost environment OneTap should work without need for [approval](https://developers.google.com/identity/one-tap/web/get-started).

**Comment by RaphaelJenni** [comment]
I will check that.

**Comment by choopage** [comment]
Hi @RaphaelJenni is your onetap working?

**Comment by RaphaelJenni** [comment]
Haven'thad the time to look further into it. Will keep you posted.

**Comment by RaphaelJenni** [comment]
Works for me.

Followed: 904881165672-atf98n8fte5iqflf3g3g9esf3rrmgjq5.apps.googleusercontent.com and https://developers.google.com/identity/one-tap/web/get-started

**Comment by RaphaelJenni** [comment]
```
const goolgeOneTapConfiguration: AuthProviderWithCustomConfig = {
  provider: AuthProvider.Google,
  customConfig: {
    authMethod: 'https://accounts.google.com',
    clientId: 'xxx.apps.googleusercontent.com'
  }
};
```

![image](https://user-images.githubusercontent.com/14369284/41509339-86143da6-7252-11e8-9735-4233e7bbcf18.png)

**Comment by choopage** [comment]
Hi @RaphaelJenni 

Thank you for your guide. It's working now. I missed something that you highlighted above.
