### ISSUE TITLE
feat: Add forRoot & forFeature

### ISSUE THREAD

**Issue by choopage** [RaphaelJenni/FirebaseUI-Angular#57]
I.e. ngrx has forRoot & forFeature https://stackoverflow.com/questions/46348412/what-is-the-difference-between-storemodule-forroot-and-storemodule-forfeature 

For FirebaseUI-Angular by having .forRoot that initialises in the AppModule, we could also have an instance of .forFeature that is being used for lazy loaded feature modules. So this would be possible to also use
  `        <firebase-ui></firebase-ui>`
in other lazy loaded modules.

**Comment by maximelafarie** [comment]
I would also love to see this feature implemented! 😉

**Comment by RaphaelJenni** [comment]
Will look into this this weekend

**Comment by RaphaelJenni** [comment]
So I finally had some time to check this issue. The plugin works this way anyway. You initialize the module in the main module with `forRoot`, in every other (lazy loaded) module you import it without the forRoot.

You can read more about that in here: https://medium.com/@chrishouse/when-to-use-angulars-forroot-method-400094a0ebb7

The forFeature is only ngrx to import some further sub stores. This isn't needed here.

**Comment by RaphaelJenni** [comment]
I'll close this, if anything isn't clear or I understood something wrong, feel free to open it again.

**Comment by choopage** [comment]
Hi @RaphaelJenni  feature request.

Currently there is `FirebaseUIModule.forRoot(firebaseUiAuthConfig)`

Using only `FirebaseUIModule` in lazy loaded module works.

However, what if we want a different firebaseUiAuthConfig for lazy loaded module?
For instance, firebaseUiAuthConfig has sign-in with Google, Email, and Facebook. Where as anotherFirebaseUiAuthConfig has only Continue As Guest and Email. 

Can we have `FirebaseUIModule.forFeature(anotherFirebaseUiAuthConfig)`?

**Comment by RaphaelJenni** [comment]
Sounds interesting. I will look into it in the near future.

**Comment by choopage** [comment]
Hi, for feature should override (or use its own configuration).

You are a rock star! Thanks.

**Comment by RaphaelJenni** [comment]
If you use `forRoot` in any module, it uses its own configuration/replaces the one provided in the root module for this module.

I will implement the partially overwriting as soon as I have some time left.

**Comment by choopage** [comment]
Awesome thanks. Noted.

**Comment by RaphaelJenni** [comment]
Done. Version 3.4.0 is released. Checkout the README for details instructions.

**Comment by choopage** [comment]
Wow awesome. Thanks

**Comment by choopage** [comment]
Hi @RaphaelJenni 

This feature is working. However, tos and pp is not being overwritten.
Meaning in forRoot there is tos and pp. While in forFeature, i removed tos and pp. But it is not being removed. It is still using the tos and pp of forRoot.

The correct behaviour should have been 
1) forRoot have tos and pp
2) forFeature no tos and pp
