### ISSUE TITLE
Weird deprecation warnings

### ISSUE THREAD

**Issue by jscti** [RaphaelJenni/FirebaseUI-Angular#58]
Hi there. Got two warnings from firebaseui-angular (and firebaseui) : 

> [FirebaseUiAngular] signInSuccess callback is deprecated. Please use signInSuccessWithAuthResult callback instead. To remove this warning set disableSignInSuccessCallback on the FirebaseUiConfig Object.
> [firebaseui] signInSuccess callback is deprecated. Please use signInSuccessWithAuthResult callback instead.

I only used the `signInSuccessWithAuthResult` in my template (but it's not documented (yet?)). After diging through the code, I saw that the firebaseUiAngular warning is emited independently of the use or not of either callback, which seems weird.
So well, I used disableSignInSuccessCallback=false but ... didn't understood all that.

Thanks

**Comment by RaphaelJenni** [comment]
Hello @jscti, sorry for the confusion.
I change it to this behavior yesterday. 

FirebaseUi has currently two different callbacks for the same thing. `signInSuccess` which now is deprecated and `signInSuccessWithAuthResult`.
To not break any already running stuff, I added this functionality to be able to disable it entirely.

So, if you set `disableSignInSuccessCallback` to `true`, the `signInSuccess` Callback is skipped and the warning disappears.
The flag is documented here: https://github.com/RaphaelJenni/FirebaseUI-Angular#config

In the future, this flag will be removed again and the `signInSuccess` callback dropped.

You only have to migrate from `signInSuccess` to `signInSuccessWithAuthResult`.

If it isn't clear, please ask and I'm happy to help. If you have any suggestions how to make that clearer, please tell me 😃

**Comment by jscti** [comment]
Thanks for the (super) quick answer !

Totally understood with your comment. Maybe you could : 
- add this detailed explanation in your flag documentation
- not show the warning + auto-disable-signInSuccess (for firebaseui) when `signInSuccessWithAuthResult`is properly used (and `signInSuccess` not used ..)
?

But I guess anybody having the same problem as me will fall here and understand.
Thanks
