### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by FallenRiteMonk** [RaphaelJenni/FirebaseUI-Angular#6]
I get the following typescript error:
```Namespace ''*'' has no exported member 'auth'.```
on line 4 of firebaseui.service.d.ts:
```
export declare class FirebaseUIService {
    firebaseUiInstance: firebaseui.auth.AuthUI;
    constructor(angularFireAuth: AngularFireAuth);
```
i have the following package versions:
```
angularfire2@4.0.0-rc.0
firebaseui@2.0.0
firebaseui-angular@0.3.0
firebase@4.0.0
@angular/<ALL_REQUIRED>@4.1.1
```

maybe it is also important to mention that im trying this in a ionic project.

**Comment by FallenRiteMonk** [comment]
I found a workaround, but since I'm not to familiar with type definitions, I don't know what effects on other libraries this could have? I'd be pleased if anyone could explain it to me?

To get this to work I had to comment out the following line in the ```declarations.d.ts``` file in my ionic project:
```declare module '*';```

Thanks to this, and the code from this [guide](https://firebase.google.com/docs/auth/web/cordova), I was able to get it to run and was able to login using the redirect method for google and phone login on the browser.
For some reason it still does not work on my android phone. The phone login doesn't work due to recapcha verifier not supported. The google login does the rederict the the browser as it should, i can choose the account to add and get redirected to app again, but the user is not created, meaning it is not listen in the firebase console. Still if I use the guide mentioned above, the app behaves similar, but the process works and I'm logged in as expected.

Any help on this is appreciated? Thanks

**Comment by RaphaelJenni** [comment]
I don't have this problem. But which typescript version do you have? Mine is `~2.2.0`.

**Comment by RaphaelJenni** [comment]
@FallenRiteMonk are you sure the user isn't created? Sometimes the console is a bit slow and needs a page refresh.
And I haven't tested the phone way yet, so maybe there is something fishy. I will give it a try.

**Comment by RaphaelJenni** [comment]
So the phone works for me, but I haven't implemented the options for the mobile way as firebaseui did. I will do that this weekend I hope. Maybe then it works for you.

**Comment by FallenRiteMonk** [comment]
I was using typescipt version ```2.3.2``` but also with ```~2.2.0``` everything is the same.

Yes I'm sure the user isn't created, tried reloading the page several times, and also restarting the app the subsription to the auth state returns null, meaning that login isn't successful.

Somehow I was able to finally get some kind of error. The strange thing is that is says that the signin was canceled by the user, but I'm not doing anything in that way, so there must be something that cancels my signin try. The stacktrace I get is:
```
[ 61.128s] [firebaseui] signInWithRedirect: auth/redirect-cancelled-by-user
Jf @ 0.main.js:4030
Array.concat.Hf.fd @ 0.main.js:4030
Array.concat.h.log @ 0.main.js:4027
vf @ 0.main.js:4027
f @ 0.main.js:4158
e.lb @ main.js:60050
Ad @ main.js:60053
wd @ main.js:60053
A.Re @ main.js:60052
Xc @ main.js:60044
t.invoke @ polyfills.js:3
r.run @ polyfills.js:3
(anonymous) @ polyfills.js:3
t.invokeTask @ polyfills.js:3
r.runTask @ polyfills.js:3
o @ polyfills.js:3
invoke @ polyfills.js:3
e @ polyfills.js:2
```
I know this istn't very helpful, but I'll keep trying to get a better stacktrace, one that is not uglyfied.

If there is something else that I can try or do for you let me know.

**Comment by RaphaelJenni** [comment]
Maybe you can checkout the plugin and try to find a solution in there.
I can't help you with ionic. Sorry.
But if you archive to fix it, I'm happy for a PR.

**Comment by RaphaelJenni** [comment]
Closing, because of inactivity.
