### ISSUE TITLE
Error 404 on buffer.svg

### ISSUE THREAD

**Issue by maximelafarie** [RaphaelJenni/FirebaseUI-Angular#61]
I have the following error in the Developer Console when including `<firebase-ui></firebase-ui>` in any component:

`GET http://localhost:4470/images/buffer.svg?embed 404 (Not Found)`

Screenshot below:
![image](https://user-images.githubusercontent.com/5319267/41259609-85709944-6dd4-11e8-8638-59ec8b3264d2.png)

I think there is a related issue here : firebase/firebaseui-web/issues/82

I guess this isn't really urgent, but it logs an error in the console. 😉 

I guess including `buffer.svg` in the library near the `.css` file will fix this issue.

Cheers! 🖖

**Comment by RaphaelJenni** [comment]
Will look into this this weekend

**Comment by RaphaelJenni** [comment]
You can put this into your styles.scss file:
```
@supports (-webkit-appearance:none) {
  .mdl-progress:not(.mdl-progress--indeterminate):not(.mdl-progress--indeterminate) > .auxbar,
  .mdl-progress:not(.mdl-progress__indeterminate):not(.mdl-progress__indeterminate) > .auxbar {
    mask: url(/assets/images/buffer.svg?embed) !important;
  }
}
```

and put a `buffer.svg` file into `assets/images`.
This will stop this error message.

Else I would have to host the firebaseui stylesheet myself and that would bring up some delays if there is an update.
