### ISSUE TITLE
Namespace 'firebaseui.auth' has no exported member 'AuthResult'

### ISSUE THREAD

**Issue by sgehrman** [RaphaelJenni/FirebaseUI-Angular#65]
ERROR in node_modules/firebaseui-angular/lib/firebaseui-angular-library.helper.d.ts(2,37): error TS2694: Namespace 'firebaseui.auth' has no exported member 'AuthResult'.

What did I do wrong?

**Comment by sgehrman** [comment]
nevermind, old versions of firebaseui

**Comment by sgehrman** [comment]
Updated to the latest versions of everything and still get this.

**Comment by sgehrman** [comment]
I'm assuming it should be firebase.auth.AuthResult?

**Comment by RaphaelJenni** [comment]
Do you have the `firebaseui` library installed?

Compare your dependencies with:
https://github.com/RaphaelJenni/FirebaseUI-Angular/blob/master/package.json#L22

**Comment by sgehrman** [comment]
doesn't work with latest firebaseui
I had to hard code it to "firebaseui": "3.0.0"

**Comment by sgehrman** [comment]
It would be great if you could update it to the latest firebaseui

**Comment by RaphaelJenni** [comment]
It is an open issue and I will do it asap. #63

**Comment by RaphaelJenni** [comment]
Fixed with Version 3.1.0 should be live soon.
