### ISSUE TITLE
chore: Upgrade to angularfire2 rc1 and firebaseui 2.1.1

### ISSUE THREAD

**Issue by choopage** [RaphaelJenni/FirebaseUI-Angular#7]
Upgrade to `"angularfire2": "4.0.0-rc.1"` and `"firebaseui": "2.1.1"` not working with `"firebaseui-angular": "0.3.0"`.

Current working but outdated versioning:
```
"angularfire2": "4.0.0-rc.0",
"firebaseui": "2.0.0",
"firebaseui-angular": "0.3.0"
```

Look forward to upgrade to angularfire2 rc1 and firebaseui 2.1.1.

**Comment by RaphaelJenni** [comment]
I'll do that in the comming days. :)

**Comment by RaphaelJenni** [comment]
Done. V 0.4.0 should be available on npm :)
If there are some problems I haven't seen, feel free to report an issue

**Comment by choopage** [comment]
Impressive. You're really professional. Thank you for your effort in maintaining this wonderful package.

**Comment by choopage** [comment]
There is a bug after the upgrade. 

![screen shot 2017-06-15 at 12 47 43 pm](https://user-images.githubusercontent.com/6467136/27165780-e9870c98-51c8-11e7-89b8-4b8bdeda9d67.png)

**Comment by choopage** [comment]
Correction. No bug. My bad. It's because besides upgrading to "angularfire2": "4.0.0-rc.1", "firebaseui": "2.1.1", and "firebaseui-angular": "0.4.0".

Also need to upgrade firebase sdk to `"firebase": "4.1.2"`
