### ISSUE TITLE
How to add invisible reCaptcha?

### ISSUE THREAD

**Issue by JaviRpo** [RaphaelJenni/FirebaseUI-Angular#70]

**Comment by RaphaelJenni** [comment]
Please specify.

**Comment by JaviRpo** [comment]
[Here](https://github.com/firebase/FirebaseUI-Web#configure-phone-provider) is the doc/example about it.

**Comment by RaphaelJenni** [comment]
Just add the configurations to the `customConfig` property.

```
const facebookCustomConfig: AuthProviderWithCustomConfig = {
  provider: AuthProvider.Phone,
  customConfig: {
    recaptchaParameters: {
        type: 'image', // 'audio'
        size: 'normal', // 'invisible' or 'compact'
        badge: 'bottomleft' //' bottomright' or 'inline' applies to invisible.
      },
      defaultCountry: 'GB',
      defaultNationalNumber: '1234567890',
      loginHint: '+11234567890'
  }
};



```

**Comment by JaviRpo** [comment]
Could this be a global configuration for all providers?
This because of the reCaptcha is a valid option in all providers, not only in the `AuthProvider.Phone`

e.g.
```
const firebaseUiAuthConfig: FirebaseUIAuthConfig = {
  customConfig: {
    recaptchaParameters: {
        type: 'image', // 'audio'
        size: 'normal', // 'invisible' or 'compact'
        badge: 'bottomleft' //' bottomright' or 'inline' applies to invisible.
      }
  },
  providers: [
      AuthProvider.Phone,
      AuthProvider.Google,
      AuthProvider.Facebook,
      AuthProvider.Twitter,
      AuthProvider.Github,
      AuthProvider.Password
  ],
  method: ...,
  credentialHelper: ...,
  autoUpgradeAnonymousUsers: ...,
  disableSignInSuccessCallback: ...
}
```

**Comment by RaphaelJenni** [comment]
Well, FirebaseUI lets you define it for each provider individually. And as this is just a wrapper of the original firebase UI project, I would like to leave it like that and don't add additional functionality/add additional complexity.
So short answer, please do it for each provider individually. You can create an issue on the official firebaseui repo. If they implement it, I will do it here too. 

As an option, that you don't have to write the same code 6 times you could take advantage of the spread operator:

```
const baseUiAuthConfig: AuthProviderWithCustomConfig = {
  provider: null,
  customConfig: {
    recaptchaParameters: {
        type: 'image', // 'audio'
        size: 'normal', // 'invisible' or 'compact'
        badge: 'bottomleft' //' bottomright' or 'inline' applies to invisible.
      }
  }
}


const firebaseUiAuthConfig: FirebaseUIAuthConfig = {
  providers: [
      {...baseUiAuthConfig, provider: AuthProvider.Phone},
      {...baseUiAuthConfig, provider: AuthProvider.Google},
      {...baseUiAuthConfig, provider: AuthProvider.Facebook},
      {...baseUiAuthConfig, provider: AuthProvider.Twitter},
      {...baseUiAuthConfig, provider: AuthProvider.Github},
      {...baseUiAuthConfig, provider: AuthProvider.Password}
  ],
  method: ...,
  credentialHelper: ...,
  autoUpgradeAnonymousUsers: ...,
  disableSignInSuccessCallback: ...
}
```

I hope I could help you, if you are not happy with this answer, I'm open to discuss alternatives in both of ours intrest.

PS:
FirebaseUI started to release their own typings, so I will migrate to it at some point and remove this configuration entierly.

**Comment by JaviRpo** [comment]
Thanks a lot for your answer.

**Comment by poqo** [comment]
> Just add the configurations to the `customConfig` property.
> 
> ```
> const phoneCustomConfig: AuthProviderWithCustomConfig = {
>   provider: AuthProvider.Phone,
>   customConfig: {
>     recaptchaParameters: {
>         type: 'image', // 'audio'
>         size: 'normal', // 'invisible' or 'compact'
>         badge: 'bottomleft' //' bottomright' or 'inline' applies to invisible.
>       },
>       defaultCountry: 'GB',
>       defaultNationalNumber: '1234567890',
>       loginHint: '+11234567890'
>   }
> };
> ```

Can't import AuthProviderWithCustomConfig, where it's located?
