### ISSUE TITLE
Disable auto signin

### ISSUE THREAD

**Issue by arjunyel** [RaphaelJenni/FirebaseUI-Angular#73]
Hello, thanks for the great library! How do you recommend I best disable auto signin? Heres how the official example does it https://github.com/firebase/firebaseui-web/blob/master/demo/public/app.js#L87

My use case is an app which requires login, when I logout it takes me to the login screen which then auto sign ins make it so you can never sign out.

Thanks for the help!

**Comment by RaphaelJenni** [comment]
I'm a little bit short on time. I will look into it tomorrow.

**Comment by arjunyel** [comment]
Works perfectly, thank you!
