### ISSUE TITLE
feat: Continue as guest (anonymous sign in)

### ISSUE THREAD

**Issue by anisabboud** [RaphaelJenni/FirebaseUI-Angular#74]
Support for `Continue as guest` through a new sign in provider `firebaseui.auth.AnonymousAuthProvider` was recently added to firebaseui-web v3.2.0 https://github.com/firebase/firebaseui-web/releases.

**Comment by RaphaelJenni** [comment]
I'm a little bit short on time. I will look into it tomorrow.

**Comment by RaphaelJenni** [comment]
I fix it in v3.3.0. Please read the [changelog](https://github.com/RaphaelJenni/FirebaseUI-Angular/blob/master/CHANGELOG.MD#330)
