### ISSUE TITLE
Error trying to build the sample with prod flag

### ISSUE THREAD

**Issue by SS2095** [RaphaelJenni/FirebaseUI-Angular#76]
I get the following errors when trying to build the sample with 'ng build --prod'

ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'firebase/index' in 'C:\Users\SS2095\Downloads\FirebaseUI-Angular-master\src\app'
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'firebaseui/dist/index' in 'C:\Users\SS2095\Downloads\FirebaseUI-Angular-master\src\app'

**Comment by RaphaelJenni** [comment]
Did you do all the steps described in the README for running the demo?

**Comment by SS2095** [comment]
Yes.

**Comment by RaphaelJenni** [comment]
Does `ng build` (without prod) work?

**Comment by SS2095** [comment]
Yes, it does.

**Comment by Suchandan** [comment]
I have the same issue.

```
Angular CLI: 6.1.3
Node: 10.8.0
OS: darwin x64
Angular: 6.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.7.3
@angular-devkit/build-angular      0.7.4
@angular-devkit/build-ng-packagr   0.7.4
@angular-devkit/build-optimizer    0.7.4
@angular-devkit/build-webpack      0.7.4
@angular-devkit/core               0.7.3
@angular-devkit/schematics         0.7.3
@angular/cli                       6.1.3
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.1.4
@schematics/angular                0.7.3
@schematics/update                 0.7.3
ng-packagr                         3.0.6
rxjs                               6.2.2
typescript                         2.9.2
webpack                            4.9.2
```

**Comment by Suchandan** [comment]
Hi @RaphaelJenni , Do we have any updates?

**Comment by RaphaelJenni** [comment]
I planned to look into it today. I'll keep you posted.

**Comment by RaphaelJenni** [comment]
@Suchandan @SS2095 does this also happen in your own projects?

**Comment by RaphaelJenni** [comment]
It is a problem wit AOT of angular. I'll investigate what exactly the problem is.

**Comment by RaphaelJenni** [comment]
If you disable aot it works. But the actual problem probably lies in the project/files structure of firebase.

**Comment by LennyZ71** [comment]
FYI you can run a --prod build successfully for now by disabling aot and build optimizer.
`ng build --prod --aot=false --build-optimizer=false`

**Comment by ajjnorton** [comment]
I am having the same issue.
```
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'firebase/index' in '/Users/anthonynorton/code/firebaseui-test/src/app'
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'firebaseui/dist/index' in '/Users/anthonynorton/code/firebaseui-test/src/app
```

But 
```
$ng build 
```
works

**Comment by MrDrProfX** [comment]
Same issue. I did some investigation, here are my findings @RaphaelJenni :

This issue is reproducible by importing firebase and firebase ui as follows:
```
import * as firebase from 'firebase/app';
import * as firebaseui from 'firebaseui';
```
Gives build error:
```
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'firebase/index'
```

Instead of importing the recommended way in the documentation README:
```
import * as firebase from 'firebase/app/dist/index.esm';
import * as firebaseui from 'firebaseui/dist/firebaseui.js';
```
BUT, the recommend import way gives this warning:
```
WARNING in ./src/app/app.module.ngfactory.js
25:4796-4804 "export 'auth' (imported as 'i14') was not found in 'firebase/app/dist/index.esm'
```
And completely breaks the app at runtime with this run time error:
```
app.module.ts:47 Uncaught TypeError: Cannot read property 'EmailAuthProvider' of undefined
```

**Comment by RaphaelJenni** [comment]
I found a workaround for the problem. `firebase` and `firebaseui` is no exposed by the plugin itself. If you import those from there everything works fine. See https://github.com/RaphaelJenni/FirebaseUI-Angular#prod-build-error

Please give it a try in v3.3.2 and sorry for any inconveniences.

**Comment by SS2095** [comment]
works for me. cheers!
