### ISSUE TITLE
npm WARN deprecated angularfire2@5.0.1: AngularFire has moved, we are now at @angular/fire

### ISSUE THREAD

**Issue by vnoitkumar** [RaphaelJenni/FirebaseUI-Angular#77]
Kindly update!

**Comment by RaphaelJenni** [comment]
Will do that asap.

**Comment by vnoitkumar** [comment]
Thank you!

**Comment by vnoitkumar** [comment]
I think by solving the above problem has created the below problem, Kindly look into it.

Cannot read property 'GoogleAuthProvider' of undefined at firebase.auth.GoogleAuthProvider.PROVIDER_ID
