### ISSUE TITLE
firebase-ui configuration of providers

### ISSUE THREAD

**Issue by Daaron3** [RaphaelJenni/FirebaseUI-Angular#8]
**Thank you very mutch for FirebaseUI-Angular everything work like a charm.**

Please where I can change change configuration for providers?

Like 
- requireDisplayName
- scopes for facebook
- recaptha parameters
- redirect with success 

Thank you for your answer.

**Comment by RaphaelJenni** [comment]
I haven't implemented that yet. But I can do that for you.
I will do it in the comming days.

**Comment by RaphaelJenni** [comment]
Or you can do a PR

**Comment by RaphaelJenni** [comment]
@Daaron3 What do you mean with the "redirect with success". The default firebase way is a hard redirect. But Angular is a single page app, so that would't be the angular way. I can implement a angular-router redirect if you want.

**Comment by Daaron3** [comment]
Thank you very mutch, 

sign in options works perfectly, I setup them in getUIAuthConfig rigidly but it works.

signInSuccess works too, but I must change callbabacks: signInSuccess to true.

Yes, you are right, I will have to write my own function with @angular/router to redirect after sign in.

**Comment by RaphaelJenni** [comment]
Ok, in that case I finalize the custom config option and release than a new version.

**Comment by RaphaelJenni** [comment]
Done. Version 0.4.1 is available on npm. Check the README and the CHANGELOG.
