### ISSUE TITLE
Angular route change and signInSuccessWithAuthResult binding

### ISSUE THREAD

**Issue by KostasInfo** [RaphaelJenni/FirebaseUI-Angular#81]
Hello, I would appreciate some help with an issue I am facing. I have a component (SigninComponent) that renders 
<firebase-ui
    (signInSuccessWithAuthResult)="successCallback($event)"
    (signInFailure)="errorCallback($event)"></firebase-ui>

When you enter the route for the first time ("/signin") and login or signup the "successCallback" is called on the SigninComponent giving the FirebaseUISignInSuccessWithAuthResult object . If you navigate away to another route, logout and then return to the signin route, the firebase widget is rendered you can sign-in or signup  but on successful login  the successCallback($event) is not triggered.  You have to refresh the browser.  

You can subscribe to angularFireAuth.authState  but it doesn't give you access to FirebaseUISignInSuccessWithAuthResult object where you can check if the user isNew and go for example to a two step signup scenario.  

How can you have the signInSuccessWithAuthResult triggered every time you login.

Is there a workaround around this or am I missing something? 

Thank you.

**Comment by RaphaelJenni** [comment]
Hello, have you tested the demo app for this use case? 
I feel like it worked for me. But I have to check it again. Can you create a sample repo or StackBlitz?

**Comment by KostasInfo** [comment]
It is the simplest app. 
Steps to reproduce. 

1. Replace environment.ts firebaseConfig with your configuration.
2. run the app. press sign, then login to firebase you will see successCallback being triggered, press the button to go to the home page, press logout and then press signin again, login to firebase and then you will notice that successCallback is not being called. 

If at any time you refresh the browser, successCallback  works again.

[fireroute.zip](https://github.com/RaphaelJenni/FirebaseUI-Angular/files/2576208/fireroute.zip)

**Comment by RaphaelJenni** [comment]
Thanks for the demo. I can reproduce the problem. 

I will look into it and come back to you as soon as I find a solution.

**Comment by RaphaelJenni** [comment]
I found out what the problem is. Looking for a fix now.

**Comment by RaphaelJenni** [comment]
I release a new beta version.
`npm install firebaseui-angular@beta`

Please give it a try and verify that it is working for you.

**Comment by RaphaelJenni** [comment]
@KostasInfo did you check it out?

**Comment by KostasInfo** [comment]
Thank you. 
From a quick check I did, it works.
