### ISSUE TITLE
email-link method

### ISSUE THREAD

**Issue by salmoro** [RaphaelJenni/FirebaseUI-Angular#84]
Is the email-link method available with this package? I don't see `emailLinkSignIn` property exposed in the config.
Thanks

**Comment by salmoro** [comment]
My apologies! It is exposed I was looking in the wrong place.

**Comment by antonellopasella-kedos** [comment]
@salmoro can you explain where is the correct place? I have the same issue

**Comment by salmoro** [comment]
@antonellopasella-kedos Sorry I have't used this library in many years so I don't know the answer.
