### ISSUE TITLE
Doc: buffer.svg?embed 404 (Not Found)

### ISSUE THREAD

**Issue by choopage** [RaphaelJenni/FirebaseUI-Angular#87]
In your documentation you mentioned to put the below code snippet in styles.scss:

```
@supports (-webkit-appearance:none) {
  .mdl-progress:not(.mdl-progress--indeterminate):not(.mdl-progress--indeterminate) > .auxbar,
  .mdl-progress:not(.mdl-progress__indeterminate):not(.mdl-progress__indeterminate) > .auxbar {
    mask: url(/assets/images/buffer.svg?embed) !important;
  }
}
```

1) May I know for users of styles.css what should they put to fix the problem?
2) Where to download `buffer.svg`?

**Comment by RaphaelJenni** [comment]
Hi @choopage 
1. Good question, I have to check a compiled version of the scss file, but currently I'm a bit short on time, so I can't promise you a quick answer.
2. It's open to you what buffer icon you want to use. I'm not sure if the original firebase-ui repo has an icon somewhere.

**Comment by choopage** [comment]
HI @RaphaelJenni  When you're free could you please advise on this?
