### ISSUE TITLE
Angular 4

### ISSUE THREAD

**Issue by foufrix** [RaphaelJenni/FirebaseUI-Angular#9]
Hello,

Does this module work with Angular 4 ?

I have followed all the steps here, and the module <firebase-ui> does not appear on the login page, i have no error in building nor on the page with the console

Any idea ?

Thanks in advance

**Comment by RaphaelJenni** [comment]
Yes, it does. You can compare it with the [sample project](https://github.com/RaphaelJenni/FirebaseUI-Angular/tree/master/sample). Maybe you find something.

**Comment by foufrix** [comment]
Yes found it thanks, perfect working like a charme now !

**Comment by foufrix** [comment]
Does it handle Anonymous Login ?

Thanks anyway for this perfect integration !

**Comment by RaphaelJenni** [comment]
No, that's not implemented by FirebaseUI. But you have to consider, the idea about the anonymous login is, that a user can do some stuff on your page without needing a user, but storing the data anyway. (e.g. Add some stuff to the bucket)
And then if the user wants to do something, where he has to have a user, you can convert the anonymous  user to an authenticated user.

That means, that the user himself never creates the anonymous user by himself. Hope I could answer you question.
