### ISSUE TITLE
<firebase-ui> does not render in chrome unless Incognito

### ISSUE THREAD

**Issue by JayPerfetto** [RaphaelJenni/FirebaseUI-Angular#90]
I had successfully implemented this using the instructions provided, and after a few days suddenly I am now only able to see the component render in Incognito mode in Chrome. The UI renders and works in Incognito Chrome, Firefox, Edge, and IE, but not standard chrome - any ideas as to why? My configuration seems fine given that it works in other browsers.

**Comment by RaphaelJenni** [comment]
Hey @JayPerfetto 
Do you have any extensions installed, that might prevent something from loading? Do you get some console errors?

**Comment by JayPerfetto** [comment]
Hi Raphael - I should have followed up to say that I figured this out - the issue is that if you are already logged in (ie a user object is returned to the subscription from firebase auth) the UI will not render. I was not properly redirecting the users away from my login page in this case, although there was no feedback to indicate that the UI was not rendering because the user was already automatically signed in by chrome. Would it be possible to add feedback to this effect?

Jason

**Comment by RaphaelJenni** [comment]
Nice to hear, that you solved the problem.

I'm not sure how I would add such a feedback, as I don't want to force a console log onto everyone.
Do you have any other idea? Or would it be enough to add that to the README?

**Comment by JayPerfetto** [comment]
Yea I think the read me would be sufficient, just point out that the component does not render if the user is already authenticated, and that some kind of auth handler function beyond just your RouteGuard is necessary to perform the redirect away from the page once that user object is detected.
