### ISSUE TITLE
firebaseui v4

### ISSUE THREAD

**Issue by krzcho** [RaphaelJenni/FirebaseUI-Angular#91]
Any plans on upgrade?

**Comment by RaphaelJenni** [comment]
Yes, it is on my todo list for the near future.

**Comment by RaphaelJenni** [comment]
@krzcho So I tested it with version 4. Everything seems to work.
Have you experienced any issues?

**Comment by krzcho** [comment]
I haven't tried actually
I am mainly waiting for new "immediateFederatedRedirect" option

**Comment by RaphaelJenni** [comment]
The plugin passes through the config exposed by firebaseui, so no change needed on my end.
The shouldn't be anything hindering you from using `immediateFederatedRedirect`

**Comment by krzcho** [comment]
Without the update I am not able to use this field

**Comment by RaphaelJenni** [comment]
@krzcho No, you can. Currently, the typings aren't updated by the firebaseui library, but if you use any as type everything works just fine.

As I said, I pass all the configurations straight through to the firebaseui library.

**Comment by krzcho** [comment]
Could you please just release updated package?

**Comment by RaphaelJenni** [comment]
Why should I release a new version with no changes?!

**Comment by RaphaelJenni** [comment]
Just run `npm install firebaseui@latest` and you are good to go.

**Comment by krzcho** [comment]
> Why should I release a new version with no changes?!

To reflect compatibility with new libraries within package.json

**Comment by RaphaelJenni** [comment]
So it's a matter of peerDependencies?

**Comment by krzcho** [comment]
hmm, just dependencies?

**Comment by RaphaelJenni** [comment]
Yes, there is absolutely no change needed to be compliant with firebaseui@4

**Comment by krzcho** [comment]
I will try `npm install firebaseui@latest` but it seems a little hack to me
Pure `npm update` should do the job but it isn't due to dependencies in your package.json

**Comment by RaphaelJenni** [comment]
Does `npm update` update major versions?
And didn't you had `firebaseui` in your package.json?

**Comment by krzcho** [comment]
ok, it seems you are right: it was mine package.json restricting firebaseui upgrade, not your package; thx

**Comment by krzcho** [comment]
However... I see following warnings

> npm WARN firebaseui-angular@3.4.2 requires a peer of @angular/common@^6.1.2 but none is installed. You must install peer dependencies yourself.
> npm WARN firebaseui-angular@3.4.2 requires a peer of @angular/core@^6.1.2 but none is installed. You must install peer dependencies yourself.
> npm WARN firebaseui-angular@3.4.2 requires a peer of @angular/fire@5.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN firebaseui-angular@3.4.2 requires a peer of firebaseui@^3.2.0 but none is installed. You must install peer dependencies yourself.
> npm WARN firebaseui-angular@3.4.2 requires a peer of firebase@^5.3.1 but none is installed. You must install peer dependencies yourself.

as I already have newer versions of those libs not matching above version specifications

**Comment by RaphaelJenni** [comment]
Alright I will fix that.
